-------------------------- Invisible objects
txd = engineLoadTXD("brak.txd")
engineImportTXD(txd, 858)
col = engineLoadCOL ("brak.col")
engineReplaceCOL (col, 858)
dff = engineLoadDFF("brak.dff", 0)
engineReplaceModel(dff, 858)
engineSetModelLODDistance(858, 600)
-----------------------------------------
txd = engineLoadTXD("brak.txd")
engineImportTXD(txd, 904)
col = engineLoadCOL ("brak.col")
engineReplaceCOL (col, 904)
dff = engineLoadDFF("brak.dff", 0)
engineReplaceModel(dff, 904)
engineSetModelLODDistance(904, 600)
-----------------------------------------
txd = engineLoadTXD("brak.txd")
engineImportTXD(txd, 885)
col = engineLoadCOL ("brak.col")
engineReplaceCOL (col, 885)
dff = engineLoadDFF("brak.dff", 0)
engineReplaceModel(dff, 885)
engineSetModelLODDistance(885, 600)
-----------------------------------------
txd = engineLoadTXD("brak.txd")
engineImportTXD(txd, 889)
col = engineLoadCOL ("brak.col")
engineReplaceCOL (col, 889)
dff = engineLoadDFF("brak.dff", 0)
engineReplaceModel(dff, 889)
engineSetModelLODDistance(889, 600)
-----------------------------------------
txd = engineLoadTXD("brak.txd")
engineImportTXD(txd, 881)
col = engineLoadCOL ("brak.col")
engineReplaceCOL (col, 881)
dff = engineLoadDFF("brak.dff", 0)
engineReplaceModel(dff, 881)
engineSetModelLODDistance(881, 600)
-----------------------------------------
txd = engineLoadTXD("brak.txd")
engineImportTXD(txd, 882)
col = engineLoadCOL ("brak.col")
engineReplaceCOL (col, 882)
dff = engineLoadDFF("brak.dff", 0)
engineReplaceModel(dff, 882)
engineSetModelLODDistance(882, 600)
-----------------------------------------
txd = engineLoadTXD("brak.txd")
engineImportTXD(txd, 891)
col = engineLoadCOL ("brak.col")
engineReplaceCOL (col, 891)
dff = engineLoadDFF("brak.dff", 0)
engineReplaceModel(dff, 891)
engineSetModelLODDistance(891, 600)
-----------------------------------------
txd = engineLoadTXD("brak.txd")
engineImportTXD(txd, 884)
col = engineLoadCOL ("brak.col")
engineReplaceCOL (col, 884)
dff = engineLoadDFF("brak.dff", 0)
engineReplaceModel(dff, 884)
engineSetModelLODDistance(884, 600)
-----------------------------------------
txd = engineLoadTXD("brak.txd")
engineImportTXD(txd, 883)
col = engineLoadCOL ("brak.col")
engineReplaceCOL (col, 883)
dff = engineLoadDFF("brak.dff", 0)
engineReplaceModel(dff, 883)
engineSetModelLODDistance(883, 600)
-----------------------------------------


