
texShader1 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/1.png")
dxSetShaderValue(texShader1,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader1,"grass4dirtyb")
engineApplyShaderToWorldTexture(texShader1,"desmuddesgrsblend_sw")
engineApplyShaderToWorldTexture(texShader1,"dirty256")
engineApplyShaderToWorldTexture(texShader1,"redstones01_lod")
engineApplyShaderToWorldTexture(texShader1,"redstones01_256")
engineApplyShaderToWorldTexture(texShader1,"desertgravelsand")
engineApplyShaderToWorldTexture(texShader1,"wash_grnd_mess1_128")
engineApplyShaderToWorldTexture(texShader1,"fredblklodlawn")
engineApplyShaderToWorldTexture(texShader1,"manns02_lod")
engineApplyShaderToWorldTexture(texShader1,"vinbloklawnlod")
engineApplyShaderToWorldTexture(texShader1,"manns02_lod")
engineApplyShaderToWorldTexture(texShader1,"sjmlaelodf996")
engineApplyShaderToWorldTexture(texShader1,"sjmlaelodf991")
engineApplyShaderToWorldTexture(texShader1,"sjmlaeloda5")
engineApplyShaderToWorldTexture(texShader1,"lanloddrygrss1")
engineApplyShaderToWorldTexture(texShader1,"fredblklodlawn")
engineApplyShaderToWorldTexture(texShader1,"sjmlaelodf992")
engineApplyShaderToWorldTexture(texShader1,"lae2ground2_lod")
engineApplyShaderToWorldTexture(texShader1,"rydrbkyrd_lod")
engineApplyShaderToWorldTexture(texShader1,"hubland5_lod")
engineApplyShaderToWorldTexture(texShader1,"hubland4_lod")
engineApplyShaderToWorldTexture(texShader1,"hubland3_lod")
engineApplyShaderToWorldTexture(texShader1,"hubgrass_lod")
engineApplyShaderToWorldTexture(texShader1,"lae2landhub2_lod")
engineApplyShaderToWorldTexture(texShader1,"lae2landhub1_lod")
engineApplyShaderToWorldTexture(texShader1,"hubland7_lod")
engineApplyShaderToWorldTexture(texShader1,"laeidlelod1")
engineApplyShaderToWorldTexture(texShader1,"idlegrou01lod")
engineApplyShaderToWorldTexture(texShader1,"sjmlaeloda92")
engineApplyShaderToWorldTexture(texShader1,"sjmlaeloda93")
engineApplyShaderToWorldTexture(texShader1,"sjmlaeloda94")
engineApplyShaderToWorldTexture(texShader1,"sjmlaeloda99")
engineApplyShaderToWorldTexture(texShader1,"sjmlodb1")
engineApplyShaderToWorldTexture(texShader1,"sjmlodd1")
engineApplyShaderToWorldTexture(texShader1,"sjmlode1")
engineApplyShaderToWorldTexture(texShader1,"sjmscorclawn3")
engineApplyShaderToWorldTexture(texShader1,"grass_dirt_64hv")
engineApplyShaderToWorldTexture(texShader1,"sjmlodb8")
engineApplyShaderToWorldTexture(texShader1,"sjmlodc1")
engineApplyShaderToWorldTexture(texShader1,"sjmlodc9")
engineApplyShaderToWorldTexture(texShader1,"las2_dirtlod")
engineApplyShaderToWorldTexture(texShader1,"grasslaelod1")
engineApplyShaderToWorldTexture(texShader1,"lascliffacelod")
engineApplyShaderToWorldTexture(texShader1,"gravelawn_lod")
engineApplyShaderToWorldTexture(texShader1,"grassdeadbrn_lod")
engineApplyShaderToWorldTexture(texShader1,"gravelawn_lod")
engineApplyShaderToWorldTexture(texShader1,"gravelawn_lod")
engineApplyShaderToWorldTexture(texShader1,"gravelawn_lod")
engineApplyShaderToWorldTexture(texShader1,"gravelawn_lod")
engineApplyShaderToWorldTexture(texShader1,"gravelawn_lod")
engineApplyShaderToWorldTexture(texShader1,"canalwest_lod")
engineApplyShaderToWorldTexture(texShader1,"japlazalaw_lod")
engineApplyShaderToWorldTexture(texShader1,"lawland08_lod")
engineApplyShaderToWorldTexture(texShader1,"lawvengrnd_lod")
engineApplyShaderToWorldTexture(texShader1,"gaz13law_lod2")
engineApplyShaderToWorldTexture(texShader1,"gaz8law_lod")
engineApplyShaderToWorldTexture(texShader1,"bevgrnd03b_lawlod")
engineApplyShaderToWorldTexture(texShader1,"lod_queenland4")
engineApplyShaderToWorldTexture(texShader1,"golfcourselod_sfs_b")
engineApplyShaderToWorldTexture(texShader1,"golfcourselod_sfs_a")
engineApplyShaderToWorldTexture(texShader1,"lod_sfsefiregrnd")
engineApplyShaderToWorldTexture(texShader1,"garselod")
engineApplyShaderToWorldTexture(texShader1,"lod_queenland3")
engineApplyShaderToWorldTexture(texShader1,"lod_bxhsegnd1")
engineApplyShaderToWorldTexture(texShader1,"lod_bxhsegnd10")
engineApplyShaderToWorldTexture(texShader1,"lod_bxhsegnd9")
engineApplyShaderToWorldTexture(texShader1,"lod_bxhsegnd2")
engineApplyShaderToWorldTexture(texShader1,"lod_bxhsegnd4")
engineApplyShaderToWorldTexture(texShader1,"lod_bxhsegnd3")
engineApplyShaderToWorldTexture(texShader1,"lod_sfs068_d")
engineApplyShaderToWorldTexture(texShader1,"lodmemorialgroundsfscm1")
engineApplyShaderToWorldTexture(texShader1,"lod_bxhsegnd5")
engineApplyShaderToWorldTexture(texShader1,"lod_bxhsegnd6")
engineApplyShaderToWorldTexture(texShader1,"lod_bxhsegnd7")
engineApplyShaderToWorldTexture(texShader1,"lod_bxhsegnd8")
engineApplyShaderToWorldTexture(texShader1,"lodcitysquare_sfs")
engineApplyShaderToWorldTexture(texShader1,"tempgrasslod1")
engineApplyShaderToWorldTexture(texShader1,"lodkalleys1_sfe")
engineApplyShaderToWorldTexture(texShader1,"lodepark_sfe")
engineApplyShaderToWorldTexture(texShader1,"bigvicgrnd_lod")
engineApplyShaderToWorldTexture(texShader1,"bigvicgrnd_lod")
engineApplyShaderToWorldTexture(texShader1,"buglod1")
engineApplyShaderToWorldTexture(texShader1,"churchlod")
engineApplyShaderToWorldTexture(texShader1,"asfnsjm9i")
engineApplyShaderToWorldTexture(texShader1,"asfnsjm9h")
engineApplyShaderToWorldTexture(texShader1,"asfnsjm93")
engineApplyShaderToWorldTexture(texShader1,"asfnsjm94")
engineApplyShaderToWorldTexture(texShader1,"vgsshospgro_lod")
engineApplyShaderToWorldTexture(texShader1,"vegasxrefhse1")
engineApplyShaderToWorldTexture(texShader1,"vegasxrefhse17")
engineApplyShaderToWorldTexture(texShader1,"grassgrn_lod")
engineApplyShaderToWorldTexture(texShader1,"vegascollege01")
engineApplyShaderToWorldTexture(texShader1,"ce_librarylod")
engineApplyShaderToWorldTexture(texShader1,"ws_patchygravellod")
engineApplyShaderToWorldTexture(texShader1,"desmudlod")
engineApplyShaderToWorldTexture(texShader1,"grass_dry_64hv")
engineApplyShaderToWorldTexture(texShader1,"oldflowerbed")
engineApplyShaderToWorldTexture(texShader1,"vgsncorpbld_lod")
engineApplyShaderToWorldTexture(texShader1,"vgn_ground11_lod")
engineApplyShaderToWorldTexture(texShader1,"vrockcafed_lod")
engineApplyShaderToWorldTexture(texShader1,"vgnorthcoast02_lod")
engineApplyShaderToWorldTexture(texShader1,"vgn_ground13_lod")
engineApplyShaderToWorldTexture(texShader1,"brngrss2stonesb")
engineApplyShaderToWorldTexture(texShader1,"grassdead1blnd")
engineApplyShaderToWorldTexture(texShader1,"hiway2sand1a")
engineApplyShaderToWorldTexture(texShader1,"hiwaygravel1_256")
engineApplyShaderToWorldTexture(texShader1,"hiwayblend1_256")
engineApplyShaderToWorldTexture(texShader1,"hiwaygravel1_lod")
engineApplyShaderToWorldTexture(texShader1,"des_dirt1_lod")
engineApplyShaderToWorldTexture(texShader1,"des_dirt2blend")
engineApplyShaderToWorldTexture(texShader1,"grasstype4_mudblend")
engineApplyShaderToWorldTexture(texShader1,"forestfloor256_blenddirt")
engineApplyShaderToWorldTexture(texShader1,"grasstype4_mudblend")
engineApplyShaderToWorldTexture(texShader1,"sjmlaelodf91")
engineApplyShaderToWorldTexture(texShader1,"rocklaelod1")
engineApplyShaderToWorldTexture(texShader1,"dirtkb_64hv_lod")
engineApplyShaderToWorldTexture(texShader1,"sjmlaelodf9")
engineApplyShaderToWorldTexture(texShader1,"sjmlaelodf4")
engineApplyShaderToWorldTexture(texShader1,"sjmlaelodf2")
engineApplyShaderToWorldTexture(texShader1,"barrio1_lod")
engineApplyShaderToWorldTexture(texShader1,"bballblok_lod")
engineApplyShaderToWorldTexture(texShader1,"lae2ground6_lod")
engineApplyShaderToWorldTexture(texShader1,"gangblk1_lod")
engineApplyShaderToWorldTexture(texShader1,"sjmlaelodf92")
engineApplyShaderToWorldTexture(texShader1,"sjmlaelodf98")
engineApplyShaderToWorldTexture(texShader1,"grasstype7_lod")
engineApplyShaderToWorldTexture(texShader1,"compurch_lod")
engineApplyShaderToWorldTexture(texShader1,"golfgrass_lod")
engineApplyShaderToWorldTexture(texShader1,"loddesgreengrass")
engineApplyShaderToWorldTexture(texShader1,"des_dirt1grasslod")
engineApplyShaderToWorldTexture(texShader1,"ce_groundtp02")
engineApplyShaderToWorldTexture(texShader1,"tenniscourt1_256")
engineApplyShaderToWorldTexture(texShader1,"golf_hvygras_cpark")
engineApplyShaderToWorldTexture(texShader1,"desmud_lod")
engineApplyShaderToWorldTexture(texShader1,"desmudtrail2")
engineApplyShaderToWorldTexture(texShader1,"grasslod")
engineApplyShaderToWorldTexture(texShader1,"vgsecoast02_lod")
engineApplyShaderToWorldTexture(texShader1,"grass_lod")
engineApplyShaderToWorldTexture(texShader1,"lod_bunnybase")
engineApplyShaderToWorldTexture(texShader1,"lodbballgroound1")
engineApplyShaderToWorldTexture(texShader1,"yardgrass1_lod")
engineApplyShaderToWorldTexture(texShader1,"sandgrndlod")
engineApplyShaderToWorldTexture(texShader1,"vgwestbildlod3")
engineApplyShaderToWorldTexture(texShader1,"vgn_ground2_lod")
engineApplyShaderToWorldTexture(texShader1,"vgn_ground1_lod")
engineApplyShaderToWorldTexture(texShader1,"vgnvrock_lod")
engineApplyShaderToWorldTexture(texShader1,"vgn_ground6_lod")
engineApplyShaderToWorldTexture(texShader1,"dirtblendlitlod")
engineApplyShaderToWorldTexture(texShader1,"forestfloor256lod")
engineApplyShaderToWorldTexture(texShader1,"forestfloorgrasslod")
engineApplyShaderToWorldTexture(texShader1,"ws_traingravelblend")
engineApplyShaderToWorldTexture(texShader1,"grassdead1blndlod")
engineApplyShaderToWorldTexture(texShader1,"grassdead1lod")
engineApplyShaderToWorldTexture(texShader1,"dirtblendlit")
engineApplyShaderToWorldTexture(texShader1,"was_scrpyd_ground_engblox")
engineApplyShaderToWorldTexture(texShader1,"grassgrn256")
engineApplyShaderToWorldTexture(texShader1,"grassdeep1")
engineApplyShaderToWorldTexture(texShader1,"grass10_grassdeep1")
engineApplyShaderToWorldTexture(texShader1,"was_scrpyd_ground_muddier")
engineApplyShaderToWorldTexture(texShader1,"was_scrpyd_ground_mudcorner")
engineApplyShaderToWorldTexture(texShader1,"was_scrpyd_ground_muddark")
engineApplyShaderToWorldTexture(texShader1,"was_scrpyd_ground_mudedge")
engineApplyShaderToWorldTexture(texShader1,"was_scrpyd_ground_mud_edge")
engineApplyShaderToWorldTexture(texShader1,"was_scrpyd_ground_mud_edge")
engineApplyShaderToWorldTexture(texShader1,"was_scrpyd_ground_mud_cnr")
engineApplyShaderToWorldTexture(texShader1,"des_dirt1")
engineApplyShaderToWorldTexture(texShader1,"des_ripplsand")
engineApplyShaderToWorldTexture(texShader1,"sandgrnd128")
engineApplyShaderToWorldTexture(texShader1,"des_roadedge1")
engineApplyShaderToWorldTexture(texShader1,"des_dirtgrassmixbmp")
engineApplyShaderToWorldTexture(texShader1,"des_grass2dirt1")
engineApplyShaderToWorldTexture(texShader1,"desgrassbrn")
engineApplyShaderToWorldTexture(texShader1,"brngrss2stones")
engineApplyShaderToWorldTexture(texShader1,"des_roadedge2")
engineApplyShaderToWorldTexture(texShader1,"des_oldrunway")
engineApplyShaderToWorldTexture(texShader1,"des_oldrunwayblend")
engineApplyShaderToWorldTexture(texShader1,"des_scrub1")
engineApplyShaderToWorldTexture(texShader1,"des_rocky1")
engineApplyShaderToWorldTexture(texShader1,"des_rocky1_dirt1")
engineApplyShaderToWorldTexture(texShader1,"grassdeadbrn256")
engineApplyShaderToWorldTexture(texShader1,"des_pave_trackstart")
engineApplyShaderToWorldTexture(texShader1,"desgreengrass")
engineApplyShaderToWorldTexture(texShader1,"sw_grass01")
engineApplyShaderToWorldTexture(texShader1,"sw_grass01a")
engineApplyShaderToWorldTexture(texShader1,"des_dirt1lod")
engineApplyShaderToWorldTexture(texShader1,"venturas_fwend")
engineApplyShaderToWorldTexture(texShader1,"bow_church_grass_gen")
engineApplyShaderToWorldTexture(texShader1,"bow_church_grass_alt")
engineApplyShaderToWorldTexture(texShader1,"lombard_lod")
engineApplyShaderToWorldTexture(texShader1,"ws_drysand")
engineApplyShaderToWorldTexture(texShader1,"lodsfsbeach4")
engineApplyShaderToWorldTexture(texShader1,"lodsfsbeach3")
engineApplyShaderToWorldTexture(texShader1,"grasstype10")
engineApplyShaderToWorldTexture(texShader1,"grasstype4-3")
engineApplyShaderToWorldTexture(texShader1,"grasstype3")
engineApplyShaderToWorldTexture(texShader1,"desgrassbrnlod")
engineApplyShaderToWorldTexture(texShader1,"des_grass2dirt1lod")
engineApplyShaderToWorldTexture(texShader1,"brngrss2stoneslod")
engineApplyShaderToWorldTexture(texShader1,"desgrasandblend")
engineApplyShaderToWorldTexture(texShader1,"desgreengrasslod")
engineApplyShaderToWorldTexture(texShader1,"desgrasandblend_lod")
engineApplyShaderToWorldTexture(texShader1,"desgrassbrn_lod")
engineApplyShaderToWorldTexture(texShader1,"bow_grass_gryard")
engineApplyShaderToWorldTexture(texShader1,"bow_church_grass_gen_lod")
engineApplyShaderToWorldTexture(texShader1,"bow_church_grass_lod")
engineApplyShaderToWorldTexture(texShader1,"desgrassbrnsnd")
engineApplyShaderToWorldTexture(texShader1,"des_scrub1_dirt1lod")
engineApplyShaderToWorldTexture(texShader1,"des_scrub1lod")
engineApplyShaderToWorldTexture(texShader1,"des_grass2scrublod")
engineApplyShaderToWorldTexture(texShader1,"des_dirt2gygrass")
engineApplyShaderToWorldTexture(texShader1,"desgrassbrn_grn")
engineApplyShaderToWorldTexture(texShader1,"des_dirt2gygrasslod")
engineApplyShaderToWorldTexture(texShader1,"des_roadedge1lod")
engineApplyShaderToWorldTexture(texShader1,"des_roadedge2lod")
engineApplyShaderToWorldTexture(texShader1,"desgreengrasslod")
engineApplyShaderToWorldTexture(texShader1,"sl_sfngrass01")
engineApplyShaderToWorldTexture(texShader1,"lodslgrass01")
engineApplyShaderToWorldTexture(texShader1,"grasslong256")
engineApplyShaderToWorldTexture(texShader1,"yardgrass1")
engineApplyShaderToWorldTexture(texShader1,"grasspave256")
engineApplyShaderToWorldTexture(texShader1,"grasspatch_64hv")
engineApplyShaderToWorldTexture(texShader1,"dirtkb_64hv")
engineApplyShaderToWorldTexture(texShader1,"dirtgaz64b")
engineApplyShaderToWorldTexture(texShader1,"desertgravelgrass256lod")
engineApplyShaderToWorldTexture(texShader1,"redcliffroof_la")
engineApplyShaderToWorldTexture(texShader1,"grasstype4_forestblend")
engineApplyShaderToWorldTexture(texShader1,"newcrop3")
engineApplyShaderToWorldTexture(texShader1,"grasstype10_4blend")
engineApplyShaderToWorldTexture(texShader1,"grasstype4")
engineApplyShaderToWorldTexture(texShader1,"grasstype4_mudblend")
engineApplyShaderToWorldTexture(texShader1,"grassgrnbrnx256")
engineApplyShaderToWorldTexture(texShader1,"grass10forest")
engineApplyShaderToWorldTexture(texShader1,"grasstype7")
engineApplyShaderToWorldTexture(texShader1,"des_dirt1grass")
engineApplyShaderToWorldTexture(texShader1,"ws_patchygravel")
engineApplyShaderToWorldTexture(texShader1,"grasstype4blndtodirt")
engineApplyShaderToWorldTexture(texShader1,"desertstones256forestmix")
engineApplyShaderToWorldTexture(texShader1,"grasstype4_mudblend")
engineApplyShaderToWorldTexture(texShader1,"forestfloor256mudblend")
engineApplyShaderToWorldTexture(texShader1,"des_scrub1_dirt1b")
engineApplyShaderToWorldTexture(texShader1,"des_scrub1_dirt1a")
engineApplyShaderToWorldTexture(texShader1,"vgn_ground8_lod")
engineApplyShaderToWorldTexture(texShader1,"vgn_ground7_lod")
engineApplyShaderToWorldTexture(texShader1,"con2sand1a")
engineApplyShaderToWorldTexture(texShader1,"vgn_ground4_lod")
engineApplyShaderToWorldTexture(texShader1,"vgn_ground3_lod")
engineApplyShaderToWorldTexture(texShader1,"con2sand1b")
engineApplyShaderToWorldTexture(texShader1,"con2sand1c")
engineApplyShaderToWorldTexture(texShader1,"concretedust2_line")
engineApplyShaderToWorldTexture(texShader1,"vgn_ground5_lod")
engineApplyShaderToWorldTexture(texShader1,"vgn_ground10_lod")
engineApplyShaderToWorldTexture(texShader1,"vgn_ground9_lod")
engineApplyShaderToWorldTexture(texShader1,"des_scrub1_dirt1_lod")
engineApplyShaderToWorldTexture(texShader1,"des_dirt1_glfhvy")
engineApplyShaderToWorldTexture(texShader1,"golf_heavygrass")
engineApplyShaderToWorldTexture(texShader1,"golf_greengrass")
engineApplyShaderToWorldTexture(texShader1,"golf_fairway1")
engineApplyShaderToWorldTexture(texShader1,"golf_fairway3")
engineApplyShaderToWorldTexture(texShader1,"seabed")
engineApplyShaderToWorldTexture(texShader1,"vegasgolflod1")
engineApplyShaderToWorldTexture(texShader1,"vegasgolflod2")
engineApplyShaderToWorldTexture(texShader1,"golf_fairway3")
engineApplyShaderToWorldTexture(texShader1,"vegasgolflod3")
engineApplyShaderToWorldTexture(texShader1,"sfn_grass1")
engineApplyShaderToWorldTexture(texShader1,"asfnsjm6")
engineApplyShaderToWorldTexture(texShader1,"des_dirt1_grass")
engineApplyShaderToWorldTexture(texShader1,"vgsecoast05_lod")
engineApplyShaderToWorldTexture(texShader1,"grassdry_lod")
engineApplyShaderToWorldTexture(texShader1,"forestfloor256")
engineApplyShaderToWorldTexture(texShader1,"forestfloorgrass")
engineApplyShaderToWorldTexture(texShader1,"forestfloorblendb")
engineApplyShaderToWorldTexture(texShader1,"des_dirt2grgrass")
engineApplyShaderToWorldTexture(texShader1,"grasstype4_10")
engineApplyShaderToWorldTexture(texShader1,"golf_fairway2")
engineApplyShaderToWorldTexture(texShader1,"golf_gravelpath")
engineApplyShaderToWorldTexture(texShader1,"des_dirt2dedgrass")
engineApplyShaderToWorldTexture(texShader1,"grassdead1blnd")
engineApplyShaderToWorldTexture(texShader1,"desertgravelgrass256")
engineApplyShaderToWorldTexture(texShader1,"desmud")
engineApplyShaderToWorldTexture(texShader1,"desmudgrass")
engineApplyShaderToWorldTexture(texShader1,"grass")
engineApplyShaderToWorldTexture(texShader1,"desmuddesgrsblend")
engineApplyShaderToWorldTexture(texShader1,"desertstones256grass")
engineApplyShaderToWorldTexture(texShader1,"desstones_dirt1")
engineApplyShaderToWorldTexture(texShader1,"sw_grass01lod")
engineApplyShaderToWorldTexture(texShader1,"sw_grass01alod")
engineApplyShaderToWorldTexture(texShader1,"grassdry_128hv")
engineApplyShaderToWorldTexture(texShader1,"grassgrnbrn256")
engineApplyShaderToWorldTexture(texShader1,"desertgryard256grs2")
engineApplyShaderToWorldTexture(texShader1,"des_scrub1_dirt1")
engineApplyShaderToWorldTexture(texShader1,"des_scrub1")
engineApplyShaderToWorldTexture(texShader1,"ce_apartsbaselod")
engineApplyShaderToWorldTexture(texShader1,"sw_path1")
engineApplyShaderToWorldTexture(texShader1,"sw_copgrass01")
engineApplyShaderToWorldTexture(texShader1,"desertgryard256grs2lod")
engineApplyShaderToWorldTexture(texShader1,"concretedust2_lod")
engineApplyShaderToWorldTexture(texShader1,"grassgrnbrn256lod")
engineApplyShaderToWorldTexture(texShader1,"lodboxtmp20")
engineApplyShaderToWorldTexture(texShader1,"sf_garden3")
engineApplyShaderToWorldTexture(texShader1,"lodboxtmp09")
engineApplyShaderToWorldTexture(texShader1,"lodxbld4_sfwa_a")
engineApplyShaderToWorldTexture(texShader1,"lodxbld4_sfw73_b")
engineApplyShaderToWorldTexture(texShader1,"sfwlodgrndnew2")
engineApplyShaderToWorldTexture(texShader1,"sf_garden1_lod")
engineApplyShaderToWorldTexture(texShader1,"sf_garden3_lod")
engineApplyShaderToWorldTexture(texShader1,"lod_parkground")
engineApplyShaderToWorldTexture(texShader1,"adetalod")
engineApplyShaderToWorldTexture(texShader1,"ground01law2_lod")
engineApplyShaderToWorldTexture(texShader1,"century02b_lod")
engineApplyShaderToWorldTexture(texShader1,"countgrndlaw2_lod")
engineApplyShaderToWorldTexture(texShader1,"greystones01_128")

texShader2 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/2.png")
dxSetShaderValue(texShader2,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader2,"des_dirttrack1rlod")
engineApplyShaderToWorldTexture(texShader2,"des_dirttrack1")
engineApplyShaderToWorldTexture(texShader2,"des_quarryrd")
engineApplyShaderToWorldTexture(texShader2,"des_quarryrdl")
engineApplyShaderToWorldTexture(texShader2,"des_dirttrack1lod")
engineApplyShaderToWorldTexture(texShader2,"grass_path_128hv")
engineApplyShaderToWorldTexture(texShader2,"macpath_lae")

texShader3 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/3.png")
dxSetShaderValue(texShader3,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader3,"desmudtrail3")
engineApplyShaderToWorldTexture(texShader3,"sw_farmroad01lod")
engineApplyShaderToWorldTexture(texShader3,"sw_farmroad01")
engineApplyShaderToWorldTexture(texShader3,"cw2_weeroad1")
engineApplyShaderToWorldTexture(texShader3,"dirttracksgrass256")
engineApplyShaderToWorldTexture(texShader3,"grassdirtblend")
engineApplyShaderToWorldTexture(texShader3,"desmudtrail")
engineApplyShaderToWorldTexture(texShader3,"was_scrpyd_ground_track_crv")
engineApplyShaderToWorldTexture(texShader3,"dirttracksgrass256lod")
engineApplyShaderToWorldTexture(texShader3,"desmudtrail2lod")

texShader4 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/4.png")
dxSetShaderValue(texShader4,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader4,"des_dirttrackl")
engineApplyShaderToWorldTexture(texShader4,"des_dirttrackllod")

texShader5 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/5.png")
dxSetShaderValue(texShader5,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader5,"des_dirttrack1r")
engineApplyShaderToWorldTexture(texShader5,"des_quarryrdr")

texShader6 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/6.png")
dxSetShaderValue(texShader6,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader6,"desgreengrasstrckend")

texShader7 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/7.png")
dxSetShaderValue(texShader7,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader7,"des_dirttrackx")

texShader8 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/8.png")
dxSetShaderValue(texShader8,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader8,"des_dirt2lod")
engineApplyShaderToWorldTexture(texShader8,"des_dirt2")
engineApplyShaderToWorldTexture(texShader8,"des_dirtgrassmixc")
engineApplyShaderToWorldTexture(texShader8,"des_dirtgrassmixb")
engineApplyShaderToWorldTexture(texShader8,"des_dirtgrassmixbmp")
engineApplyShaderToWorldTexture(texShader8,"des_crackeddirt1")
engineApplyShaderToWorldTexture(texShader8,"grass4dirty")
engineApplyShaderToWorldTexture(texShader8,"lod_desbhus_grnd")

texShader9 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/9.png")
dxSetShaderValue(texShader9,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader9,"des_dirt2grasslod")
engineApplyShaderToWorldTexture(texShader9,"roadblendcunt")
engineApplyShaderToWorldTexture(texShader9,"grass10des_dirt2")
engineApplyShaderToWorldTexture(texShader9,"grass4_des_dirt2")
engineApplyShaderToWorldTexture(texShader9,"grasstype3dirt")
engineApplyShaderToWorldTexture(texShader9,"des_dirtgrassmix_grass4")
engineApplyShaderToWorldTexture(texShader9,"des_dirt2grass")

texShader10 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/10.png")
dxSetShaderValue(texShader10,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader10,"des_dirt2stones")

texShader11 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/11.png")
dxSetShaderValue(texShader11,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader11,"des_dirt2 trackl")

texShader12 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/12.png")
dxSetShaderValue(texShader12,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader12,"des_dirt2tracklod")
engineApplyShaderToWorldTexture(texShader12,"des_dirt2track")

texShader13 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/13.png")
dxSetShaderValue(texShader13,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader13,"des_dirt2trackr")

texShader14 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/14.png")
dxSetShaderValue(texShader14,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader14,"sjmloda94")
engineApplyShaderToWorldTexture(texShader14,"grass_128hvlod")
engineApplyShaderToWorldTexture(texShader14,"lodgrounds04_sfs_a")
engineApplyShaderToWorldTexture(texShader14,"asfnsjm9za")
engineApplyShaderToWorldTexture(texShader14,"asfnsjm9z")
engineApplyShaderToWorldTexture(texShader14,"sjmsfw2")
engineApplyShaderToWorldTexture(texShader14,"lodgrass128hv_blend_")
engineApplyShaderToWorldTexture(texShader14,"lod_sfse_dirt")
engineApplyShaderToWorldTexture(texShader14,"freewayboxgrnd")
engineApplyShaderToWorldTexture(texShader14,"lod_sboxbld4")
engineApplyShaderToWorldTexture(texShader14,"lodgrass_128hv")
engineApplyShaderToWorldTexture(texShader14,"burbhaus02lod")
engineApplyShaderToWorldTexture(texShader14,"forestfloor3_forest")
engineApplyShaderToWorldTexture(texShader14,"forestfloorblendded")
engineApplyShaderToWorldTexture(texShader14,"burbhaus04lod")
engineApplyShaderToWorldTexture(texShader14,"sw_dirt01lod")
engineApplyShaderToWorldTexture(texShader14,"bigburbgrndlod")
engineApplyShaderToWorldTexture(texShader14,"burbhaus01lod")
engineApplyShaderToWorldTexture(texShader14,"burbhaus03lod")
engineApplyShaderToWorldTexture(texShader14,"woodhausgrdnlod")
engineApplyShaderToWorldTexture(texShader14,"bow_church_dirt")
engineApplyShaderToWorldTexture(texShader14,"sw_crops")
engineApplyShaderToWorldTexture(texShader14,"sw_dirt01")
engineApplyShaderToWorldTexture(texShader14,"grass_128hv")
engineApplyShaderToWorldTexture(texShader14,"grass128hv_blend_")
engineApplyShaderToWorldTexture(texShader14,"lodsfsbeach5")
engineApplyShaderToWorldTexture(texShader14,"sw_stones")
engineApplyShaderToWorldTexture(texShader14,"sw_stoneslod")
engineApplyShaderToWorldTexture(texShader14,"mudyforest256")
engineApplyShaderToWorldTexture(texShader14,"sjmscorclawn")
engineApplyShaderToWorldTexture(texShader14,"stones256128")
engineApplyShaderToWorldTexture(texShader14,"sandnew_law")
engineApplyShaderToWorldTexture(texShader14,"sandnew_lawlod")
engineApplyShaderToWorldTexture(texShader14,"labeachbx_lod")
engineApplyShaderToWorldTexture(texShader14,"sjmloda993")
engineApplyShaderToWorldTexture(texShader14,"beachlod01_law2")
engineApplyShaderToWorldTexture(texShader14,"forestfloorblend")
engineApplyShaderToWorldTexture(texShader14,"forestfloor3")
engineApplyShaderToWorldTexture(texShader14,"sw_sand")
engineApplyShaderToWorldTexture(texShader14,"grasstype5")
engineApplyShaderToWorldTexture(texShader14,"stones256")
engineApplyShaderToWorldTexture(texShader14,"grassdeep256")
engineApplyShaderToWorldTexture(texShader14,"cw2_mountdirt")
engineApplyShaderToWorldTexture(texShader14,"cw2_mounttrail")
engineApplyShaderToWorldTexture(texShader14,"cw2_mountroad")
engineApplyShaderToWorldTexture(texShader14,"mountainskree_stones256")
engineApplyShaderToWorldTexture(texShader14,"cw2_mounttrailblank")
engineApplyShaderToWorldTexture(texShader14,"sw_sandlod")
engineApplyShaderToWorldTexture(texShader14,"grifnewtex1x_las")
engineApplyShaderToWorldTexture(texShader14,"grifnewtex1b")
engineApplyShaderToWorldTexture(texShader14,"dirt64b2")
engineApplyShaderToWorldTexture(texShader14,"sjmlahus28")
engineApplyShaderToWorldTexture(texShader14,"ffbranch_mountdirt")
engineApplyShaderToWorldTexture(texShader14,"forestfloorbranch256")
engineApplyShaderToWorldTexture(texShader14,"sandstonemixb")
engineApplyShaderToWorldTexture(texShader14,"sjmloda97")
engineApplyShaderToWorldTexture(texShader14,"sjmloda93")
engineApplyShaderToWorldTexture(texShader14,"ws_football_lines2")
engineApplyShaderToWorldTexture(texShader14,"grass_lawn_128hv")
engineApplyShaderToWorldTexture(texShader14,"grasslawnfade_256")
engineApplyShaderToWorldTexture(texShader14,"cw2_mountdirtlod")
engineApplyShaderToWorldTexture(texShader14,"sjmloda994")
engineApplyShaderToWorldTexture(texShader14,"dirt64b2_lod")
engineApplyShaderToWorldTexture(texShader14,"dirttracksforest")
engineApplyShaderToWorldTexture(texShader14,"grasstype510")
engineApplyShaderToWorldTexture(texShader14,"forestfloor4")
engineApplyShaderToWorldTexture(texShader14,"sw_cropslod")
engineApplyShaderToWorldTexture(texShader14,"obhilltex1")
engineApplyShaderToWorldTexture(texShader14,"sjmloda996")
engineApplyShaderToWorldTexture(texShader14,"desertstones256")
engineApplyShaderToWorldTexture(texShader14,"desertstones256lod")

texShader15 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/15.png")
dxSetShaderValue(texShader15,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader15,"grasstype1-4")
engineApplyShaderToWorldTexture(texShader15,"grasstype510_10")
engineApplyShaderToWorldTexture(texShader15,"grasstype4_staw")
engineApplyShaderToWorldTexture(texShader15,"forestfloor_sones256")
engineApplyShaderToWorldTexture(texShader15,"forestfloor256_blenddirt")
engineApplyShaderToWorldTexture(texShader15,"sw_stonesgrass")
engineApplyShaderToWorldTexture(texShader15,"sw_stonesgrasslod")
engineApplyShaderToWorldTexture(texShader15,"sl_sfngrssdrt01")
engineApplyShaderToWorldTexture(texShader15,"desegravelgrassroadla")
engineApplyShaderToWorldTexture(texShader15,"grass4dirtytrans")
engineApplyShaderToWorldTexture(texShader15,"sw_sandgrass4")
engineApplyShaderToWorldTexture(texShader15,"grasstype5_4")
engineApplyShaderToWorldTexture(texShader15,"grass10_stones256")
engineApplyShaderToWorldTexture(texShader15,"grass10dirt")
engineApplyShaderToWorldTexture(texShader15,"cw2_mountdirt2grass")
engineApplyShaderToWorldTexture(texShader15,"cw2_mountdirt2forest")
engineApplyShaderToWorldTexture(texShader15,"desmud2forstfloor")
engineApplyShaderToWorldTexture(texShader15,"cw2_mountdirt2grasslod")

texShader16 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/16.png")
dxSetShaderValue(texShader16,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader16,"forest_rocks")
engineApplyShaderToWorldTexture(texShader16,"sw_dirt01_forestblend")
engineApplyShaderToWorldTexture(texShader16,"ws_drysand2grass")
engineApplyShaderToWorldTexture(texShader16,"bow_church_dirt_to_grass_side_t")
engineApplyShaderToWorldTexture(texShader16,"grasstype5_dirt")
engineApplyShaderToWorldTexture(texShader16,"grasstype4blndtomud")
engineApplyShaderToWorldTexture(texShader16,"grasstype5_desdirt")

texShader17 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/17.png")
dxSetShaderValue(texShader17,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader17,"grassshort2long256")
engineApplyShaderToWorldTexture(texShader17,"sw_sandgrass")
engineApplyShaderToWorldTexture(texShader17,"sw_sandgrasslod")

texShader18 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/18.png")
dxSetShaderValue(texShader18,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader18,"sw_grassb01")
engineApplyShaderToWorldTexture(texShader18,"sw_grassb01lod")

texShader19 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/19.png")
dxSetShaderValue(texShader19,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader19,"newrockgrass_sfw")
engineApplyShaderToWorldTexture(texShader19,"lasclifface")
engineApplyShaderToWorldTexture(texShader19,"sjmloda99")
engineApplyShaderToWorldTexture(texShader19,"rockwall2_lae2")
engineApplyShaderToWorldTexture(texShader19,"lod_newrockgrass_sfw")

texShader20 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/20.png")
dxSetShaderValue(texShader20,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader20,"cw2_mountdirtscree")

texShader21 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/21.png")
dxSetShaderValue(texShader21,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader21,"grassdead1")
engineApplyShaderToWorldTexture(texShader21,"des_scrub1_lod")
engineApplyShaderToWorldTexture(texShader21,"des_scrub1")
engineApplyShaderToWorldTexture(texShader21,"desertgryard256")
engineApplyShaderToWorldTexture(texShader21,"desertgryard256lod")
engineApplyShaderToWorldTexture(texShader21,"sfn_rockhole")

texShader22 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/22.png")
dxSetShaderValue(texShader22,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader22,"des_scrub1_dirt1")
engineApplyShaderToWorldTexture(texShader22,"des_dirt2dedgrass")

texShader23 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/23.png")
dxSetShaderValue(texShader23,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader23,"des_grass2scrub")
engineApplyShaderToWorldTexture(texShader23,"desgreengrassmix")
engineApplyShaderToWorldTexture(texShader23,"desgreengrassmixlod")

texShader24 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/24.png")
dxSetShaderValue(texShader24,"gTexture",Shader)

texShader25 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/25.png")
dxSetShaderValue(texShader25,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader25,"lodrocksea_sfw")
engineApplyShaderToWorldTexture(texShader25,"des_redrock1")
engineApplyShaderToWorldTexture(texShader25,"des_redrock2")
engineApplyShaderToWorldTexture(texShader25,"sm_rock2_desert")
engineApplyShaderToWorldTexture(texShader25,"des_redrockmidlod")
engineApplyShaderToWorldTexture(texShader25,"sw_rockgrass1lod")
engineApplyShaderToWorldTexture(texShader25,"rocktbrn128blnlod")
engineApplyShaderToWorldTexture(texShader25,"cst_rock_coast_sfw")
engineApplyShaderToWorldTexture(texShader25,"cst_rocksea_sfw")
engineApplyShaderToWorldTexture(texShader25,"cst_rock_undersea_sfw")
engineApplyShaderToWorldTexture(texShader25,"desgrns256")
engineApplyShaderToWorldTexture(texShader25,"rocktbrn_dirt2")
engineApplyShaderToWorldTexture(texShader25,"cw2_mountrock")
engineApplyShaderToWorldTexture(texShader25,"sw_rockgrass1")
engineApplyShaderToWorldTexture(texShader25,"rocktq128")
engineApplyShaderToWorldTexture(texShader25,"rock_country128")
engineApplyShaderToWorldTexture(texShader25,"cs_rockdetail2")
engineApplyShaderToWorldTexture(texShader25,"rocktb128")
engineApplyShaderToWorldTexture(texShader25,"greyrockbig")
engineApplyShaderToWorldTexture(texShader25,"vgs_rockmid1a")
engineApplyShaderToWorldTexture(texShader25,"sfe_rock1")
engineApplyShaderToWorldTexture(texShader25,"sfe_rock2")
engineApplyShaderToWorldTexture(texShader25,"sfe_rock3")
engineApplyShaderToWorldTexture(texShader25,"desclifftypebs")
engineApplyShaderToWorldTexture(texShader25,"rockwall1_lae2")
engineApplyShaderToWorldTexture(texShader25,"lod_rock_coast_sfw")
engineApplyShaderToWorldTexture(texShader25,"asfnsjm9zd")
engineApplyShaderToWorldTexture(texShader25,"rocktbrn128")
engineApplyShaderToWorldTexture(texShader25,"rocktbrn128lod")


texShader26 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/26.png")
dxSetShaderValue(texShader26,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader26,"asfnsjm9zb")
engineApplyShaderToWorldTexture(texShader26,"sw_rock1a")
engineApplyShaderToWorldTexture(texShader26,"sw_rockgrassb2lod")
engineApplyShaderToWorldTexture(texShader26,"grassbrn2rockbrn_lod")
engineApplyShaderToWorldTexture(texShader26,"sw_rockgrassb1")
engineApplyShaderToWorldTexture(texShader26,"rocktq128_forestblend2")
engineApplyShaderToWorldTexture(texShader26,"cunt_toprock")
engineApplyShaderToWorldTexture(texShader26,"rocktq128_grass4blend")
engineApplyShaderToWorldTexture(texShader26,"grassbrn2rockbrng2")
engineApplyShaderToWorldTexture(texShader26,"cuntbrnclifftop")
engineApplyShaderToWorldTexture(texShader26,"rocktq128_dirt")
engineApplyShaderToWorldTexture(texShader26,"rocktq128_forestblend")
engineApplyShaderToWorldTexture(texShader26,"rocktq128blender")
engineApplyShaderToWorldTexture(texShader26,"grassbrn2rockbrng")
engineApplyShaderToWorldTexture(texShader26,"grassbrn2rockbrn")
engineApplyShaderToWorldTexture(texShader26,"grassbrn2rockbrnlod")
engineApplyShaderToWorldTexture(texShader26,"rocktbrn128blndlit")
engineApplyShaderToWorldTexture(texShader26,"rocktbrn128blndlitlod")
engineApplyShaderToWorldTexture(texShader26,"rocktbrn128_lod")
engineApplyShaderToWorldTexture(texShader26,"grassbrn2rockbrnglod")
engineApplyShaderToWorldTexture(texShader26,"sw_rockgrassb2")
engineApplyShaderToWorldTexture(texShader26,"sw_rockgrassb1lod")
engineApplyShaderToWorldTexture(texShader26,"desclifftypebsmix")
engineApplyShaderToWorldTexture(texShader26,"desclifftypebsmixlod")
engineApplyShaderToWorldTexture(texShader26,"rocktq128_dirt")


texShader27 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/27.png")
dxSetShaderValue(texShader27,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader27,"blendrock2grasslod")
engineApplyShaderToWorldTexture(texShader27,"cunt_botrock")
engineApplyShaderToWorldTexture(texShader27,"cuntbrncliffbtmbmp")
engineApplyShaderToWorldTexture(texShader27,"vgs_rockbot1a")
engineApplyShaderToWorldTexture(texShader27,"vgs_rockbot1a_lod")
engineApplyShaderToWorldTexture(texShader27,"blendrock2grgrass")

texShader28 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/28.png")
dxSetShaderValue(texShader28,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader28,"rocktbrn128bllod")
engineApplyShaderToWorldTexture(texShader28,"rocktbrn128blnd")
engineApplyShaderToWorldTexture(texShader28,"rocktbrn128blndlit")
engineApplyShaderToWorldTexture(texShader28,"rocktbrn128blndlitlod")
engineApplyShaderToWorldTexture(texShader28,"sfncn_rockgrass3")

texShader29 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/29.png")
dxSetShaderValue(texShader29,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader29,"asfnsjm9zc")
engineApplyShaderToWorldTexture(texShader29,"dt_road2grasstype4")
engineApplyShaderToWorldTexture(texShader29,"golf_grassrock")
engineApplyShaderToWorldTexture(texShader29,"rock_country128blnd")

texShader30 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/30.png")
dxSetShaderValue(texShader30,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader30,"redclifftop256")
engineApplyShaderToWorldTexture(texShader30,"redclifftoplod")

texShader31 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/31.png")
dxSetShaderValue(texShader31,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader31,"des_redrockbot")
engineApplyShaderToWorldTexture(texShader31,"des_redrockbotlod")

texShader32 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/32.png")
dxSetShaderValue(texShader32,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader32,"des_redrockmid")

texShader33 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/33.png")
dxSetShaderValue(texShader33,"gTexture",Shader)

texShader34 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/34.png")
dxSetShaderValue(texShader34,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader34,"des_yelrock")
engineApplyShaderToWorldTexture(texShader34,"des_rocky1")
engineApplyShaderToWorldTexture(texShader34,"des_yelrocklod")

texShader35 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/35.png")
dxSetShaderValue(texShader35,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader35,"lhroadlod")
engineApplyShaderToWorldTexture(texShader35,"lodsferoad1")
engineApplyShaderToWorldTexture(texShader35,"lodsferoad2")
engineApplyShaderToWorldTexture(texShader35,"tar_1linex2lod")
engineApplyShaderToWorldTexture(texShader35,"tar_1linefreewylod")
engineApplyShaderToWorldTexture(texShader35,"sf_junction1")
engineApplyShaderToWorldTexture(texShader35,"sf_junction2")
engineApplyShaderToWorldTexture(texShader35,"snpedtest1blend")
engineApplyShaderToWorldTexture(texShader35,"roaddgrassblnd")
engineApplyShaderToWorldTexture(texShader35,"tar_1line256hvblend")
engineApplyShaderToWorldTexture(texShader35,"tar_1line256hv_lod")
engineApplyShaderToWorldTexture(texShader35,"1linefreewylod")
engineApplyShaderToWorldTexture(texShader35,"motocross_256")
engineApplyShaderToWorldTexture(texShader35,"greycrossing")
engineApplyShaderToWorldTexture(texShader35,"tar_1line256hv")
engineApplyShaderToWorldTexture(texShader35,"tar1line256hv_lod")
engineApplyShaderToWorldTexture(texShader35,"tar_1line256hvlod")
engineApplyShaderToWorldTexture(texShader35,"lod_cn2_xrdbit")
engineApplyShaderToWorldTexture(texShader35,"lod_cn2_troad")
engineApplyShaderToWorldTexture(texShader35,"des_1line256")
engineApplyShaderToWorldTexture(texShader35,"des_1linetar")
engineApplyShaderToWorldTexture(texShader35,"des_1lineend")
engineApplyShaderToWorldTexture(texShader35,"desert_1line256")
engineApplyShaderToWorldTexture(texShader35,"desert_1linetar")
engineApplyShaderToWorldTexture(texShader35,"tar_1linefreewy")
engineApplyShaderToWorldTexture(texShader35,"tar_1line256hvblenddrt")
engineApplyShaderToWorldTexture(texShader35,"tar_1line256hvblend2")
engineApplyShaderToWorldTexture(texShader35,"tar_1line256hvtodirt")
engineApplyShaderToWorldTexture(texShader35,"tar_1line256hvtodirtlod")
engineApplyShaderToWorldTexture(texShader35,"tar_1line256hvlightsand")
engineApplyShaderToWorldTexture(texShader35,"tar_1line256hvlightsandlod")
engineApplyShaderToWorldTexture(texShader35,"lod_des_road1")
engineApplyShaderToWorldTexture(texShader35,"tar_1line256hvblenddrtdot")
engineApplyShaderToWorldTexture(texShader35,"sf_junction5")
engineApplyShaderToWorldTexture(texShader35,"sf_junction3")
engineApplyShaderToWorldTexture(texShader35,"crossing_law2")
engineApplyShaderToWorldTexture(texShader35,"crossing_law")
engineApplyShaderToWorldTexture(texShader35,"craproad2_lae")
engineApplyShaderToWorldTexture(texShader35,"tar_1line256hvgtravel")
engineApplyShaderToWorldTexture(texShader35,"tar_lineslipway")
engineApplyShaderToWorldTexture(texShader35,"tar_venturasjoin")
engineApplyShaderToWorldTexture(texShader35,"tar_freewyright")
engineApplyShaderToWorldTexture(texShader35,"tar_freewyleft")
engineApplyShaderToWorldTexture(texShader35,"tar_leftright_lod")
engineApplyShaderToWorldTexture(texShader35,"tar_1lineblenddrt_lod")
engineApplyShaderToWorldTexture(texShader35,"sjmlas2lod5n")
engineApplyShaderToWorldTexture(texShader35,"countryroads")
engineApplyShaderToWorldTexture(texShader35,"vegasdirtyroad3_256")
engineApplyShaderToWorldTexture(texShader35,"crossing_law3")
engineApplyShaderToWorldTexture(texShader35,"dt_road_stoplinea")
engineApplyShaderToWorldTexture(texShader35,"vgsn_fmt_road_lod")
engineApplyShaderToWorldTexture(texShader35,"sfroad4_lod")
engineApplyShaderToWorldTexture(texShader35,"sfroad3_lod")
engineApplyShaderToWorldTexture(texShader35,"road_junction2")
engineApplyShaderToWorldTexture(texShader35,"road_junction")
engineApplyShaderToWorldTexture(texShader35,"sjmlode4")
engineApplyShaderToWorldTexture(texShader35,"lawnroad01lod")

texShader36 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/36.png")
dxSetShaderValue(texShader36,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader36,"pier02a_lod")
engineApplyShaderToWorldTexture(texShader36,"pier1lod_law2")
engineApplyShaderToWorldTexture(texShader36,"cuntroad01_law")
engineApplyShaderToWorldTexture(texShader36,"2lanewhiteline")
engineApplyShaderToWorldTexture(texShader36,"pavroadx2pav")
engineApplyShaderToWorldTexture(texShader36,"melroadlawnlod")
engineApplyShaderToWorldTexture(texShader36,"2laneverge")
engineApplyShaderToWorldTexture(texShader36,"greypavroadlod")
engineApplyShaderToWorldTexture(texShader36,"lan2lodfreewayj2")
engineApplyShaderToWorldTexture(texShader36,"lanlodroadjunc2")
engineApplyShaderToWorldTexture(texShader36,"lanlodroadjunc1")
engineApplyShaderToWorldTexture(texShader36,"sjmlaeloda1")
engineApplyShaderToWorldTexture(texShader36,"sjmlaelod3")
engineApplyShaderToWorldTexture(texShader36,"sjmlaeloda997")
engineApplyShaderToWorldTexture(texShader36,"sjmlaeloda995")
engineApplyShaderToWorldTexture(texShader36,"sjmlaeloda95")
engineApplyShaderToWorldTexture(texShader36,"sjmlaeloda95")
engineApplyShaderToWorldTexture(texShader36,"laeroadcrnrlod")
engineApplyShaderToWorldTexture(texShader36,"sjmlodd9")
engineApplyShaderToWorldTexture(texShader36,"sjmlode2")
engineApplyShaderToWorldTexture(texShader36,"sjmlode3")
engineApplyShaderToWorldTexture(texShader36,"sjmloda98")
engineApplyShaderToWorldTexture(texShader36,"sjmlodc92")
engineApplyShaderToWorldTexture(texShader36,"sjmlodc4")
engineApplyShaderToWorldTexture(texShader36,"sjmlodc2")
engineApplyShaderToWorldTexture(texShader36,"sjmlodc3")
engineApplyShaderToWorldTexture(texShader36,"las2_bridgroad")
engineApplyShaderToWorldTexture(texShader36,"las2_block8")
engineApplyShaderToWorldTexture(texShader36,"las2_block5")
engineApplyShaderToWorldTexture(texShader36,"las2_lod17")
engineApplyShaderToWorldTexture(texShader36,"lae2rdcst3_lod")
engineApplyShaderToWorldTexture(texShader36,"lae2rdcst4_lod")
engineApplyShaderToWorldTexture(texShader36,"lae2roadiv_lod")
engineApplyShaderToWorldTexture(texShader36,"sjmlaelodf5")
engineApplyShaderToWorldTexture(texShader36,"sjmlaelodf995")
engineApplyShaderToWorldTexture(texShader36,"tar_1linex2alod")
engineApplyShaderToWorldTexture(texShader36,"lod_mountainroad_sfs")
engineApplyShaderToWorldTexture(texShader36,"lod_hilltop1_sfs")
engineApplyShaderToWorldTexture(texShader36,"lodsferoad3")
engineApplyShaderToWorldTexture(texShader36,"lodsferoad4")
engineApplyShaderToWorldTexture(texShader36,"specialroad")
engineApplyShaderToWorldTexture(texShader36,"asjmsfse96")
engineApplyShaderToWorldTexture(texShader36,"lod_freewaysliproads")
engineApplyShaderToWorldTexture(texShader36,"asfsssjm1")
engineApplyShaderToWorldTexture(texShader36,"sfroad1_lod")
engineApplyShaderToWorldTexture(texShader36,"vgscrjunction02_lod")
engineApplyShaderToWorldTexture(texShader36,"vgstjunction02_lod")
engineApplyShaderToWorldTexture(texShader36,"vgsroadlrge_lod")
engineApplyShaderToWorldTexture(texShader36,"vgstjunction03_lod")
engineApplyShaderToWorldTexture(texShader36,"lod_freewayroads")
engineApplyShaderToWorldTexture(texShader36,"roaddirtlod")
engineApplyShaderToWorldTexture(texShader36,"roadnew4blend_256")
engineApplyShaderToWorldTexture(texShader36,"hiwayoutside_256")
engineApplyShaderToWorldTexture(texShader36,"cuntetownroad1lod")
engineApplyShaderToWorldTexture(texShader36,"ce_roadverge")
engineApplyShaderToWorldTexture(texShader36,"roadnew4_256")
engineApplyShaderToWorldTexture(texShader36,"ws_freeway3")
engineApplyShaderToWorldTexture(texShader36,"hiwaymidlle_256")
engineApplyShaderToWorldTexture(texShader36,"cos_hiwaymid_256")
engineApplyShaderToWorldTexture(texShader36,"greypavroadlinelod")
engineApplyShaderToWorldTexture(texShader36,"roadnew4_256alod")
engineApplyShaderToWorldTexture(texShader36,"ws_freeway3blend")
engineApplyShaderToWorldTexture(texShader36,"hiwayend_256")
engineApplyShaderToWorldTexture(texShader36,"vegasroad1_256")
engineApplyShaderToWorldTexture(texShader36,"vegastriproad1_256")
engineApplyShaderToWorldTexture(texShader36,"striproadlod1_64")
engineApplyShaderToWorldTexture(texShader36,"vgsroad01_lod")
engineApplyShaderToWorldTexture(texShader36,"vgsroad02c_lod")
engineApplyShaderToWorldTexture(texShader36,"sl_freew2road1")
engineApplyShaderToWorldTexture(texShader36,"sjmloda992")
engineApplyShaderToWorldTexture(texShader36,"snpedtest1x2")
engineApplyShaderToWorldTexture(texShader36,"sf_tramline2")
engineApplyShaderToWorldTexture(texShader36,"roadnew4_512")
engineApplyShaderToWorldTexture(texShader36,"cunte_roadwideside")
engineApplyShaderToWorldTexture(texShader36,"vegasroad3_256")
engineApplyShaderToWorldTexture(texShader36,"vegasdirtyroad1_256")
engineApplyShaderToWorldTexture(texShader36,"vegasdirtyroad2_256")
engineApplyShaderToWorldTexture(texShader36,"vgsroadirt1_256")
engineApplyShaderToWorldTexture(texShader36,"roadcoast6_lod")
engineApplyShaderToWorldTexture(texShader36,"roadcoast5_lod")
engineApplyShaderToWorldTexture(texShader36,"vgsroad02_lod")
engineApplyShaderToWorldTexture(texShader36,"fourlanefreeway")
engineApplyShaderToWorldTexture(texShader36,"ce_4laneverge")
engineApplyShaderToWorldTexture(texShader36,"vgshiwaygras_lod")
engineApplyShaderToWorldTexture(texShader36,"hiwayinside3_256")
engineApplyShaderToWorldTexture(texShader36,"vegroadjunc1_lod")
engineApplyShaderToWorldTexture(texShader36,"vegdirtyroad2_lod")
engineApplyShaderToWorldTexture(texShader36,"vegroadjunc2_lod")
engineApplyShaderToWorldTexture(texShader36,"vgsjunction01_lod")
engineApplyShaderToWorldTexture(texShader36,"vgstjunction01_lod")
engineApplyShaderToWorldTexture(texShader36,"vgsroad02b_lod")
engineApplyShaderToWorldTexture(texShader36,"vgsroad04_lod")
engineApplyShaderToWorldTexture(texShader36,"vgsroad03_lod")
engineApplyShaderToWorldTexture(texShader36,"vgstjunction06_lod")
engineApplyShaderToWorldTexture(texShader36,"vgstjunction05_lod")
engineApplyShaderToWorldTexture(texShader36,"lombard_sfe")
engineApplyShaderToWorldTexture(texShader36,"vegasroad2_256")
engineApplyShaderToWorldTexture(texShader36,"dt_road")
engineApplyShaderToWorldTexture(texShader36,"craproad7_lae7")
engineApplyShaderToWorldTexture(texShader36,"craproad1_lae")
engineApplyShaderToWorldTexture(texShader36,"snpedtest1")
engineApplyShaderToWorldTexture(texShader36,"sjmloda991")
engineApplyShaderToWorldTexture(texShader36,"lae2hubrd_lod")
engineApplyShaderToWorldTexture(texShader36,"lae2longrd_lod")
engineApplyShaderToWorldTexture(texShader36,"lae2rdfuk_lod")
engineApplyShaderToWorldTexture(texShader36,"pinkpavroadlod")
engineApplyShaderToWorldTexture(texShader36,"freewaylae2_lod")
engineApplyShaderToWorldTexture(texShader36,"sjmlaeloda6")
engineApplyShaderToWorldTexture(texShader36,"sjmlaeloda98")
engineApplyShaderToWorldTexture(texShader36,"sl_laefreeway1")
engineApplyShaderToWorldTexture(texShader36,"lanlodroad1")
engineApplyShaderToWorldTexture(texShader36,"lawroad1_lod")
engineApplyShaderToWorldTexture(texShader36,"lawhiway_lod")
engineApplyShaderToWorldTexture(texShader36,"dualroadlod01")
engineApplyShaderToWorldTexture(texShader36,"freewaylaw2_lod")
engineApplyShaderToWorldTexture(texShader36,"lawnroad02lod")
engineApplyShaderToWorldTexture(texShader36,"lan2lodfreeway2")
engineApplyShaderToWorldTexture(texShader36,"lan2lodfreeway3")
engineApplyShaderToWorldTexture(texShader36,"lan2lodfreewayj1")
engineApplyShaderToWorldTexture(texShader36,"lawnroad03lod")
engineApplyShaderToWorldTexture(texShader36,"lan2lodfreeway1")
engineApplyShaderToWorldTexture(texShader36,"sjmlaeloda994")
engineApplyShaderToWorldTexture(texShader36,"sjmlaeloda993")
engineApplyShaderToWorldTexture(texShader36,"las2_lod18")
engineApplyShaderToWorldTexture(texShader36,"snpedtest1blnd")
engineApplyShaderToWorldTexture(texShader36,"sf_road5")
engineApplyShaderToWorldTexture(texShader36,"dt_roadblend")
engineApplyShaderToWorldTexture(texShader36,"sl_roadbutt1")
engineApplyShaderToWorldTexture(texShader36,"vgsroad05_lod")
engineApplyShaderToWorldTexture(texShader36,"vgstjunction04_lod")
engineApplyShaderToWorldTexture(texShader36,"cuntetownroad2lod")
engineApplyShaderToWorldTexture(texShader36,"roads_sfnlod64")
engineApplyShaderToWorldTexture(texShader36,"sfwbridgelod")
engineApplyShaderToWorldTexture(texShader36,"sfroad2_lod")
engineApplyShaderToWorldTexture(texShader36,"lae2_roads89_lod")
engineApplyShaderToWorldTexture(texShader36,"hiwayinsideblend3_256")

texShader37 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/37.png")
dxSetShaderValue(texShader37,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader37,"desertgravelgrassroad")

texShader38 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/38.png")
dxSetShaderValue(texShader38,"gTexture",Shader)

texShader39 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/39.png")
dxSetShaderValue(texShader39,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader39,"hiwayinside5_256")
engineApplyShaderToWorldTexture(texShader39,"hiwayinside4_256")
engineApplyShaderToWorldTexture(texShader39,"hiwayinside2_256")
engineApplyShaderToWorldTexture(texShader39,"hiwayinside_256")
engineApplyShaderToWorldTexture(texShader39,"hiwayinsideblend2_256")
engineApplyShaderToWorldTexture(texShader39,"hiwayinsideblend1_256")

texShader40 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/40.png")
dxSetShaderValue(texShader40,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader40,"vgsn_road2sand01")
engineApplyShaderToWorldTexture(texShader40,"vgsroadirt1_256")

texShader41 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/41.png")
dxSetShaderValue(texShader41,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader41,"vegaspavement3_256")
engineApplyShaderToWorldTexture(texShader41,"blendpavement2_256")
engineApplyShaderToWorldTexture(texShader41,"lod_sf_pave1")
engineApplyShaderToWorldTexture(texShader41,"lodp_sfw35_d")
engineApplyShaderToWorldTexture(texShader41,"lod_fancy_slab")
engineApplyShaderToWorldTexture(texShader41,"lodrybit3_sfw")
engineApplyShaderToWorldTexture(texShader41,"asfnsjm3")
engineApplyShaderToWorldTexture(texShader41,"asfnsjm2")
engineApplyShaderToWorldTexture(texShader41,"pavebsand256grassblended_lod")
engineApplyShaderToWorldTexture(texShader41,"pavebsand256lod")
engineApplyShaderToWorldTexture(texShader41,"kbpavement_test")
engineApplyShaderToWorldTexture(texShader41,"pavebsand256blueblend")
engineApplyShaderToWorldTexture(texShader41,"craproad5_lae")
engineApplyShaderToWorldTexture(texShader41,"sidewalk4_lae")
engineApplyShaderToWorldTexture(texShader41,"sl_pavebutt2")
engineApplyShaderToWorldTexture(texShader41,"sf_pave5")
engineApplyShaderToWorldTexture(texShader41,"sf_pave3")
engineApplyShaderToWorldTexture(texShader41,"starpave_law")
engineApplyShaderToWorldTexture(texShader41,"sf_pave4")
engineApplyShaderToWorldTexture(texShader41,"sf_pave6")
engineApplyShaderToWorldTexture(texShader41,"tilered")
engineApplyShaderToWorldTexture(texShader41,"fancy_slab128")
engineApplyShaderToWorldTexture(texShader41,"blendpavement2b_256")
engineApplyShaderToWorldTexture(texShader41,"sjmhoodlawn41")
engineApplyShaderToWorldTexture(texShader41,"sidewgrass5")
engineApplyShaderToWorldTexture(texShader41,"sidewgrass1")
engineApplyShaderToWorldTexture(texShader41,"sidewgrass2")
engineApplyShaderToWorldTexture(texShader41,"sidewgrass3")
engineApplyShaderToWorldTexture(texShader41,"sidewgrass4")
engineApplyShaderToWorldTexture(texShader41,"sidewgrass_fuked")
engineApplyShaderToWorldTexture(texShader41,"yardgrass2")
engineApplyShaderToWorldTexture(texShader41,"grassdry_path_128hv")
engineApplyShaderToWorldTexture(texShader41,"grass_concpath2")
engineApplyShaderToWorldTexture(texShader41,"sjmhoodlawn42")
engineApplyShaderToWorldTexture(texShader41,"scumtiles3_lae")
engineApplyShaderToWorldTexture(texShader41,"sidelatino1_lae")
engineApplyShaderToWorldTexture(texShader41,"dockpave_256")
engineApplyShaderToWorldTexture(texShader41,"newpavement")
engineApplyShaderToWorldTexture(texShader41,"trainground1")
engineApplyShaderToWorldTexture(texShader41,"trainground3")
engineApplyShaderToWorldTexture(texShader41,"sl_pavebutt1")
engineApplyShaderToWorldTexture(texShader41,"ws_alley_conc1")
engineApplyShaderToWorldTexture(texShader41,"sjmndukwal2")
engineApplyShaderToWorldTexture(texShader41,"craproad6_lae")
engineApplyShaderToWorldTexture(texShader41,"cos_hiwayins_256")
engineApplyShaderToWorldTexture(texShader41,"ws_nicepave")
engineApplyShaderToWorldTexture(texShader41,"sjmhoodlawn42b")
engineApplyShaderToWorldTexture(texShader41,"kbpavementblend")
engineApplyShaderToWorldTexture(texShader41,"mono4_sfe")
engineApplyShaderToWorldTexture(texShader41,"mono3_sfe")
engineApplyShaderToWorldTexture(texShader41,"pavebsand256")
engineApplyShaderToWorldTexture(texShader41,"pavebsandend")
engineApplyShaderToWorldTexture(texShader41,"pavebsand256grassblended")
engineApplyShaderToWorldTexture(texShader41,"laroad_centre1")
engineApplyShaderToWorldTexture(texShader41,"vgsn_road2sand02")
engineApplyShaderToWorldTexture(texShader41,"vegasdirtypave1_256")
engineApplyShaderToWorldTexture(texShader41,"vegasdirtypaveblend1")
engineApplyShaderToWorldTexture(texShader41,"vegasdirtypaveblend2")
engineApplyShaderToWorldTexture(texShader41,"vegasdirtypave2_256")
engineApplyShaderToWorldTexture(texShader41,"vegaspavement2_256")
engineApplyShaderToWorldTexture(texShader41,"vgsroadirt2_256")
engineApplyShaderToWorldTexture(texShader41,"laroad_offroad1")
engineApplyShaderToWorldTexture(texShader41,"road1256")
engineApplyShaderToWorldTexture(texShader41,"pavemiddirt_law")
engineApplyShaderToWorldTexture(texShader41,"backalley1_lae")

texShader42 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/42.png")
dxSetShaderValue(texShader42,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader42,"grasstype10_rail")
engineApplyShaderToWorldTexture(texShader42,"sw_traingravelb1")
engineApplyShaderToWorldTexture(texShader42,"trainground2")
engineApplyShaderToWorldTexture(texShader42,"ws_traingravel")
engineApplyShaderToWorldTexture(texShader42,"ws_traingravel_lod")
engineApplyShaderToWorldTexture(texShader42,"rail_stones256")

texShader43 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/43.png")
dxSetShaderValue(texShader43,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader43,"ws_traintrax1")
engineApplyShaderToWorldTexture(texShader43,"lod_bridgetrax")
engineApplyShaderToWorldTexture(texShader43,"vgsrailroad_lod")
engineApplyShaderToWorldTexture(texShader43,"vgs_railway04_lod")

texShader44 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/44.png")
dxSetShaderValue(texShader44,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader44,"sjmlodd92")
engineApplyShaderToWorldTexture(texShader44,"vgs_railway03_lod")
engineApplyShaderToWorldTexture(texShader44,"sjmlodd92")
engineApplyShaderToWorldTexture(texShader44,"vgs_railway02_lod")
engineApplyShaderToWorldTexture(texShader44,"vgs_railcrss_lod")
engineApplyShaderToWorldTexture(texShader44,"vgs_railway01_lod")

texShader45 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/45.png")
dxSetShaderValue(texShader45,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader45,"des_dirtgravel")

texShader46 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/46.png")
dxSetShaderValue(texShader46,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader46,"ws_wetsand")
engineApplyShaderToWorldTexture(texShader46,"lodsfsbeach1")
engineApplyShaderToWorldTexture(texShader46,"lodsfsbeach2")

texShader47 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/47.png")
dxSetShaderValue(texShader47,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader47,"ws_wetdryblendsand")

texShader48 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/48.png")
dxSetShaderValue(texShader48,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader48,"unnamed")

texShader49 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/49.png")
dxSetShaderValue(texShader49,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader49,"ws_whitewall2_top")
engineApplyShaderToWorldTexture(texShader49,"ws_whitewall2_bottom")
engineApplyShaderToWorldTexture(texShader49,"concretewall22_256")
engineApplyShaderToWorldTexture(texShader49,"ws_trans_concr")
engineApplyShaderToWorldTexture(texShader49,"ws_white_wall1")
engineApplyShaderToWorldTexture(texShader49,"labluewall")
engineApplyShaderToWorldTexture(texShader49,"ws_blocks_grey_1")
engineApplyShaderToWorldTexture(texShader49,"ws_green_wall1")
engineApplyShaderToWorldTexture(texShader49,"ws_pink_wall1")
engineApplyShaderToWorldTexture(texShader49,"hilcouwall1")
engineApplyShaderToWorldTexture(texShader49,"lacreamwall1")
engineApplyShaderToWorldTexture(texShader49,"stonewall_la")
engineApplyShaderToWorldTexture(texShader49,"ws_blocks_red_1")
engineApplyShaderToWorldTexture(texShader49,"lagreenwall")
engineApplyShaderToWorldTexture(texShader49,"ws_mixedbrick")
engineApplyShaderToWorldTexture(texShader49,"concpanel_la")
engineApplyShaderToWorldTexture(texShader49,"ws_mixedbrick")
engineApplyShaderToWorldTexture(texShader49,"ws_sandstone1")
engineApplyShaderToWorldTexture(texShader49,"wallbluetinge256")
engineApplyShaderToWorldTexture(texShader49,"ws_altz_wall10")
engineApplyShaderToWorldTexture(texShader49,"tgogg4_256")
engineApplyShaderToWorldTexture(texShader49,"ws_plasterwall1")
engineApplyShaderToWorldTexture(texShader49,"ws_hotel7")
engineApplyShaderToWorldTexture(texShader49,"ws_apartmentmankyb2")
engineApplyShaderToWorldTexture(texShader49,"ws_apartmentblue2")
engineApplyShaderToWorldTexture(texShader49,"sw_brewbrick01")
engineApplyShaderToWorldTexture(texShader49,"ws_apartmentwhite2")
engineApplyShaderToWorldTexture(texShader49,"ws_altz_wall10b")
engineApplyShaderToWorldTexture(texShader49,"ws_altz_wall8_bot")
engineApplyShaderToWorldTexture(texShader49,"ws_altz_wall7")
engineApplyShaderToWorldTexture(texShader49,"ws_fancywallpink")
engineApplyShaderToWorldTexture(texShader49,"lasunion2")
engineApplyShaderToWorldTexture(texShader49,"lasunion7")
engineApplyShaderToWorldTexture(texShader49,"bow_dlct_plstrb_genb")
engineApplyShaderToWorldTexture(texShader49,"sl_concretewall1")
engineApplyShaderToWorldTexture(texShader49,"rufwaldock1")
engineApplyShaderToWorldTexture(texShader49,"macbrij2_lae")
engineApplyShaderToWorldTexture(texShader49,"sl_concretewall1")
engineApplyShaderToWorldTexture(texShader49,"stormdrain3_nt")

texShader50 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/50.png")
dxSetShaderValue(texShader50,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader50,"retainwall1")
engineApplyShaderToWorldTexture(texShader50,"ap_tarmac")
engineApplyShaderToWorldTexture(texShader50,"concretebuild64")
engineApplyShaderToWorldTexture(texShader50,"des_panelconc")
engineApplyShaderToWorldTexture(texShader50,"a51_metal1")
engineApplyShaderToWorldTexture(texShader50,"ws_stationfloor")
engineApplyShaderToWorldTexture(texShader50,"concretegroundl1_256")
engineApplyShaderToWorldTexture(texShader50,"ws_oldpaintedyello")
engineApplyShaderToWorldTexture(texShader50,"stormdrain6")
engineApplyShaderToWorldTexture(texShader50,"concreteblock_256")
engineApplyShaderToWorldTexture(texShader50,"ws_freeway2")
engineApplyShaderToWorldTexture(texShader50,"greyground2sand")
engineApplyShaderToWorldTexture(texShader50,"vgs_rockwall01_128")
engineApplyShaderToWorldTexture(texShader50,"lod_ws_oldpainted2")
engineApplyShaderToWorldTexture(texShader50,"hospunder_law")
engineApplyShaderToWorldTexture(texShader50,"bow_sub_walltiles")
engineApplyShaderToWorldTexture(texShader50,"bonyrd_skin1")
engineApplyShaderToWorldTexture(texShader50,"lod_bonyrd_skin2")
engineApplyShaderToWorldTexture(texShader50,"clukinbell1_lod")
engineApplyShaderToWorldTexture(texShader50,"asjmsfse8")
engineApplyShaderToWorldTexture(texShader50,"asjmsfse7")
engineApplyShaderToWorldTexture(texShader50,"asjmsfse6")
engineApplyShaderToWorldTexture(texShader50,"asjmsfse5")
engineApplyShaderToWorldTexture(texShader50,"des_motelwall3")
engineApplyShaderToWorldTexture(texShader50,"stormdrain5_nt")
engineApplyShaderToWorldTexture(texShader50,"trail_wall1")
engineApplyShaderToWorldTexture(texShader50,"concretenew256128")
engineApplyShaderToWorldTexture(texShader50,"newgrnd1_128")
engineApplyShaderToWorldTexture(texShader50,"ws_rotten_concrete1")
engineApplyShaderToWorldTexture(texShader50,"slab64")
engineApplyShaderToWorldTexture(texShader50,"llas2_lod1")
engineApplyShaderToWorldTexture(texShader50,"sjmlodb7")
engineApplyShaderToWorldTexture(texShader50,"sjmlode9")
engineApplyShaderToWorldTexture(texShader50,"sjmlodb99")
engineApplyShaderToWorldTexture(texShader50,"las2_greygrnd")
engineApplyShaderToWorldTexture(texShader50,"las2_bakaly")
engineApplyShaderToWorldTexture(texShader50,"las2_concnw")
engineApplyShaderToWorldTexture(texShader50,"las2_block25")
engineApplyShaderToWorldTexture(texShader50,"newferrylod4")
engineApplyShaderToWorldTexture(texShader50,"lodhosp10")
engineApplyShaderToWorldTexture(texShader50,"newferrylod1")
engineApplyShaderToWorldTexture(texShader50,"newferrylod3")
engineApplyShaderToWorldTexture(texShader50,"newferrylod2")
engineApplyShaderToWorldTexture(texShader50,"lodpavetilealley")
engineApplyShaderToWorldTexture(texShader50,"asfnsjm5")
engineApplyShaderToWorldTexture(texShader50,"concretemankylod")
engineApplyShaderToWorldTexture(texShader50,"ws_carparknew2_lod")
engineApplyShaderToWorldTexture(texShader50,"concretegroundl1_lod")
engineApplyShaderToWorldTexture(texShader50,"lod_concretenewb256")
engineApplyShaderToWorldTexture(texShader50,"cuntw_dinerroof_lod")
engineApplyShaderToWorldTexture(texShader50,"sw_copshopr_lod")
engineApplyShaderToWorldTexture(texShader50,"carpark_128lod")
engineApplyShaderToWorldTexture(texShader50,"ce_brewery2lod")
engineApplyShaderToWorldTexture(texShader50,"newgrnd1brn_128lod")
engineApplyShaderToWorldTexture(texShader50,"sf_pave2_lod")
engineApplyShaderToWorldTexture(texShader50,"ws_carpark2lod")
engineApplyShaderToWorldTexture(texShader50,"lodcretemanky")
engineApplyShaderToWorldTexture(texShader50,"lod_genhall")
engineApplyShaderToWorldTexture(texShader50,"vgs_shopwall01_128lod")
engineApplyShaderToWorldTexture(texShader50,"concretemanky")
engineApplyShaderToWorldTexture(texShader50,"stormdrain4_nt")
engineApplyShaderToWorldTexture(texShader50,"des_facmetalsoild")
engineApplyShaderToWorldTexture(texShader50,"carpark_128")
engineApplyShaderToWorldTexture(texShader50,"conc_wall2_128h")
engineApplyShaderToWorldTexture(texShader50,"parking2plain")
engineApplyShaderToWorldTexture(texShader50,"parking2")
engineApplyShaderToWorldTexture(texShader50,"concretenewb256")
engineApplyShaderToWorldTexture(texShader50,"sf_pave2")
engineApplyShaderToWorldTexture(texShader50,"greyground256")
engineApplyShaderToWorldTexture(texShader50,"greyground_lod")
engineApplyShaderToWorldTexture(texShader50,"ws_carpark2")
engineApplyShaderToWorldTexture(texShader50,"bow_abattoir_conc2")
engineApplyShaderToWorldTexture(texShader50,"concretebigb256128")
engineApplyShaderToWorldTexture(texShader50,"concretenewb256128")
engineApplyShaderToWorldTexture(texShader50,"beachwalk_law")
engineApplyShaderToWorldTexture(texShader50,"bow_smear_cement")
engineApplyShaderToWorldTexture(texShader50,"des_dam_conclod")
engineApplyShaderToWorldTexture(texShader50,"heliconcrete")
engineApplyShaderToWorldTexture(texShader50,"sw_pdground")
engineApplyShaderToWorldTexture(texShader50,"paveslab1")
engineApplyShaderToWorldTexture(texShader50,"concretenewgery256")
engineApplyShaderToWorldTexture(texShader50,"stormdrain7")
engineApplyShaderToWorldTexture(texShader50,"concretebig4256128")
engineApplyShaderToWorldTexture(texShader50,"lasrmd2_sjm")
engineApplyShaderToWorldTexture(texShader50,"stormdrain1b_sl")
engineApplyShaderToWorldTexture(texShader50,"cos_hiwayout_256")
engineApplyShaderToWorldTexture(texShader50,"newgrnd1brn_128")
engineApplyShaderToWorldTexture(texShader50,"tardor9")
engineApplyShaderToWorldTexture(texShader50,"laslacma5")
engineApplyShaderToWorldTexture(texShader50,"lanroof1lod")
engineApplyShaderToWorldTexture(texShader50,"sjmndukwal3")
engineApplyShaderToWorldTexture(texShader50,"ws_carparknew2a")
engineApplyShaderToWorldTexture(texShader50,"tar_blenddrtwhiteline")
engineApplyShaderToWorldTexture(texShader50,"metalox64")
engineApplyShaderToWorldTexture(texShader50,"sf_tramcross")
engineApplyShaderToWorldTexture(texShader50,"highshopwall1256")
engineApplyShaderToWorldTexture(texShader50,"ws_sub_pen_conc")
engineApplyShaderToWorldTexture(texShader50,"ws_carpark1")
engineApplyShaderToWorldTexture(texShader50,"ws_carparknew2")
engineApplyShaderToWorldTexture(texShader50,"ws_carparknew1")
engineApplyShaderToWorldTexture(texShader50,"pavetilealley256128")
engineApplyShaderToWorldTexture(texShader50,"stonewalls1_la")
engineApplyShaderToWorldTexture(texShader50,"gravelkb2_128")
engineApplyShaderToWorldTexture(texShader50,"mono1_sfe")
engineApplyShaderToWorldTexture(texShader50,"mono2_sfe")
engineApplyShaderToWorldTexture(texShader50,"vgs_shopwall01_128")
engineApplyShaderToWorldTexture(texShader50,"des_ranchwall1lod")
engineApplyShaderToWorldTexture(texShader50,"plaintarmac1")
engineApplyShaderToWorldTexture(texShader50,"stormdrain_lod")
engineApplyShaderToWorldTexture(texShader50,"lanstormdrn2lod")
engineApplyShaderToWorldTexture(texShader50,"sjmlaeloda991")
engineApplyShaderToWorldTexture(texShader50,"las2_drum1")
engineApplyShaderToWorldTexture(texShader50,"tanstucco1_la")
engineApplyShaderToWorldTexture(texShader50,"sjmlodb95")
engineApplyShaderToWorldTexture(texShader50,"sjmlodb94")
engineApplyShaderToWorldTexture(texShader50,"sjmlodb93")
engineApplyShaderToWorldTexture(texShader50,"sjmlodb92")
engineApplyShaderToWorldTexture(texShader50,"sjmlodb98")
engineApplyShaderToWorldTexture(texShader50,"sjmlodb97")
engineApplyShaderToWorldTexture(texShader50,"sjmlodb96")
engineApplyShaderToWorldTexture(texShader50,"ws_sub_pen_conc3")
engineApplyShaderToWorldTexture(texShader50,"ws_airpt_concrete")
engineApplyShaderToWorldTexture(texShader50,"ws_runwaytarmac")
engineApplyShaderToWorldTexture(texShader50,"asjmsfse8")
engineApplyShaderToWorldTexture(texShader50,"asjmsfse7")
engineApplyShaderToWorldTexture(texShader50,"asjmsfse6")
engineApplyShaderToWorldTexture(texShader50,"asjmsfse5")
engineApplyShaderToWorldTexture(texShader50,"asjmsfse9")
engineApplyShaderToWorldTexture(texShader50,"asjmsfse91")
engineApplyShaderToWorldTexture(texShader50,"asjmsfse92")
engineApplyShaderToWorldTexture(texShader50,"cuntroad01_lawlod")
engineApplyShaderToWorldTexture(texShader50,"des_decocafe_lod")
engineApplyShaderToWorldTexture(texShader50,"stormdrain3_ntlod")
engineApplyShaderToWorldTexture(texShader50,"stormdrain5_ntlod")
engineApplyShaderToWorldTexture(texShader50,"blocklod")
engineApplyShaderToWorldTexture(texShader50,"bow_abattoir_conc2lod")
engineApplyShaderToWorldTexture(texShader50,"asfnsjm9g")
engineApplyShaderToWorldTexture(texShader50,"ws_carparknew2lod")
engineApplyShaderToWorldTexture(texShader50,"alleygroundb256")
engineApplyShaderToWorldTexture(texShader50,"support_256")


texShader51 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/51.png")
dxSetShaderValue(texShader51,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader51,"forumstand1_lae")
engineApplyShaderToWorldTexture(texShader51,"gb_nastybar02")
engineApplyShaderToWorldTexture(texShader51,"des_ranchwall1")
engineApplyShaderToWorldTexture(texShader51,"block2lod")
engineApplyShaderToWorldTexture(texShader51,"block2_low")
engineApplyShaderToWorldTexture(texShader51,"ws_whiteplaster_top")
engineApplyShaderToWorldTexture(texShader51,"ws_whiteplaster_btm")
engineApplyShaderToWorldTexture(texShader51,"ws_oldpainted2rusty")
engineApplyShaderToWorldTexture(texShader51,"ws_fluorescent1")
engineApplyShaderToWorldTexture(texShader51,"pavea256")
engineApplyShaderToWorldTexture(texShader51,"ws_tunnelwall2")
engineApplyShaderToWorldTexture(texShader51,"sw_tunnel02bmp")
engineApplyShaderToWorldTexture(texShader51,"des_tunnellight")
engineApplyShaderToWorldTexture(texShader51,"ws_tunnelwall2_lod")
engineApplyShaderToWorldTexture(texShader51,"block")
engineApplyShaderToWorldTexture(texShader51,"ws_tunnelwall1")
engineApplyShaderToWorldTexture(texShader51,"ws_tunnelwall2smoked")
engineApplyShaderToWorldTexture(texShader51,"block2_high")
engineApplyShaderToWorldTexture(texShader51,"block2")
engineApplyShaderToWorldTexture(texShader51,"concretebuild_lod")
engineApplyShaderToWorldTexture(texShader51,"pav_brngrass")
engineApplyShaderToWorldTexture(texShader51,"ws_oldredbrick")
engineApplyShaderToWorldTexture(texShader51,"conc_wall_stripd2128h")
engineApplyShaderToWorldTexture(texShader51,"whitewall256")
engineApplyShaderToWorldTexture(texShader51,"stonewall2_la")
engineApplyShaderToWorldTexture(texShader51,"rodeo3sjm")
engineApplyShaderToWorldTexture(texShader51,"stonewall3_la")
engineApplyShaderToWorldTexture(texShader51,"ws_bridgepavement")
engineApplyShaderToWorldTexture(texShader51,"ws_oldpainted2")
engineApplyShaderToWorldTexture(texShader51,"tuntest1las")
engineApplyShaderToWorldTexture(texShader51,"savtop")

texShader52 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/52.png")
dxSetShaderValue(texShader52,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader52,"lodrock1_128")
engineApplyShaderToWorldTexture(texShader52,"asfnsjm8")
engineApplyShaderToWorldTexture(texShader52,"greyground256128")
engineApplyShaderToWorldTexture(texShader52,"indund_64")
engineApplyShaderToWorldTexture(texShader52,"drvin_ground1")
engineApplyShaderToWorldTexture(texShader52,"parking1plain")
engineApplyShaderToWorldTexture(texShader52,"brickred2")
engineApplyShaderToWorldTexture(texShader52,"window5b")
engineApplyShaderToWorldTexture(texShader52,"parking2lod")
engineApplyShaderToWorldTexture(texShader52,"parking2plainlod")
engineApplyShaderToWorldTexture(texShader52,"sw_walltile")
engineApplyShaderToWorldTexture(texShader52,"ce_farmsilolod")
engineApplyShaderToWorldTexture(texShader52,"conchev_64hv")
engineApplyShaderToWorldTexture(texShader52,"concrete_64hv")
engineApplyShaderToWorldTexture(texShader52,"concretedust2_256128")

texShader53 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/53.png")
dxSetShaderValue(texShader53,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader53,"rock1_128")
engineApplyShaderToWorldTexture(texShader53,"hllblf2_lae")
engineApplyShaderToWorldTexture(texShader53,"bow_warehousewall")
engineApplyShaderToWorldTexture(texShader53,"badmarb1_lan")
engineApplyShaderToWorldTexture(texShader53,"bluemetal")

texShader54 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/54.jpg")
dxSetShaderValue(texShader54,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader54,"iron")
engineApplyShaderToWorldTexture(texShader54,"girder2_red_64hv")
engineApplyShaderToWorldTexture(texShader54,"barrel_64hv")
engineApplyShaderToWorldTexture(texShader54,"scratchedmetal")
engineApplyShaderToWorldTexture(texShader54,"metpat64")
engineApplyShaderToWorldTexture(texShader54,"buceta")
engineApplyShaderToWorldTexture(texShader54,"cj_lamppost1")
engineApplyShaderToWorldTexture(texShader54,"lamppost2")
engineApplyShaderToWorldTexture(texShader54,"cj_sheetmetal")
engineApplyShaderToWorldTexture(texShader54,"cj_phonebox1")
engineApplyShaderToWorldTexture(texShader54,"cj_plating")
engineApplyShaderToWorldTexture(texShader54,"billdetaily")
engineApplyShaderToWorldTexture(texShader54,"bluemetal02")
engineApplyShaderToWorldTexture(texShader54,"sw_roadsign")
engineApplyShaderToWorldTexture(texShader54,"bonyrd_skin2")
engineApplyShaderToWorldTexture(texShader54,"cabin2")
engineApplyShaderToWorldTexture(texShader54,"car1_128")
engineApplyShaderToWorldTexture(texShader54,"lastran6")
engineApplyShaderToWorldTexture(texShader54,"carwash_256")
engineApplyShaderToWorldTexture(texShader54,"roadsback01_la")
engineApplyShaderToWorldTexture(texShader54,"bbback")
engineApplyShaderToWorldTexture(texShader54,"banding9_64hv")
engineApplyShaderToWorldTexture(texShader54,"metal1_128")
engineApplyShaderToWorldTexture(texShader54,"lamppost")
engineApplyShaderToWorldTexture(texShader54,"sl_laexporail")
engineApplyShaderToWorldTexture(texShader54,"trafficlight_64")
engineApplyShaderToWorldTexture(texShader54,"lampost_16clr")
engineApplyShaderToWorldTexture(texShader54,"white64")
engineApplyShaderToWorldTexture(texShader54,"skylight_scum")
engineApplyShaderToWorldTexture(texShader54,"cabin3")
engineApplyShaderToWorldTexture(texShader54,"lod_cracktanks")
engineApplyShaderToWorldTexture(texShader54,"car2_128")
engineApplyShaderToWorldTexture(texShader54,"lastran2")
engineApplyShaderToWorldTexture(texShader54,"lastran3")
engineApplyShaderToWorldTexture(texShader54,"lastran4")

texShader55 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/55.png")
dxSetShaderValue(texShader55,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader55,"sfn_rocktbrn128")

texShader60 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/60.png")
dxSetShaderValue(texShader60,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader60,"airportmetalwall256")
engineApplyShaderToWorldTexture(texShader60,"vgnwrehse2_256")
engineApplyShaderToWorldTexture(texShader60,"vgnwrehse8_256")

texShader61 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/61.png")
dxSetShaderValue(texShader61,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader61,"vgnwrehse7_256")

texShader62 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/62.png")
dxSetShaderValue(texShader62,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader62,"vgnwrehse3_256")
engineApplyShaderToWorldTexture(texShader62,"vgnwrehse6_256")
engineApplyShaderToWorldTexture(texShader62,"vgnwrehse5_256")

texShader63 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/63.png")
dxSetShaderValue(texShader63,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader63,"frate64_blue")
engineApplyShaderToWorldTexture(texShader63,"frate64_red")
engineApplyShaderToWorldTexture(texShader63,"frate64_yellow")

texShader64 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/64.png")
dxSetShaderValue(texShader64,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader64,"frate_doors128red")
engineApplyShaderToWorldTexture(texShader64,"frate_doors64")
engineApplyShaderToWorldTexture(texShader64,"frate_doors64yellow")
engineApplyShaderToWorldTexture(texShader64,"frate_doors64128")

texShader67 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/67.png")
dxSetShaderValue(texShader67,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader67,"closedblank1_256")
engineApplyShaderToWorldTexture(texShader67,"cj_canvas3")
engineApplyShaderToWorldTexture(texShader67,"comptwall31")
engineApplyShaderToWorldTexture(texShader67,"comptwall32")

texShader68 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/68.png")
dxSetShaderValue(texShader68,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader68,"cj_rubbish1")

texShader69 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/69.png")
dxSetShaderValue(texShader69,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader69,"stormdrain1_nt")
engineApplyShaderToWorldTexture(texShader69,"lasrmd3_sjm")

texShader70 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/70.png")
dxSetShaderValue(texShader70,"gTexture",Shader)

texShader71 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/71.png")
dxSetShaderValue(texShader71,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader71,"prolaps02")

texShader72 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/72.png")
dxSetShaderValue(texShader72,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader72,"redmetal")
engineApplyShaderToWorldTexture(texShader72,"des_bytower1")
engineApplyShaderToWorldTexture(texShader72,"des_bytower1")
engineApplyShaderToWorldTexture(texShader72,"des_factower")
engineApplyShaderToWorldTexture(texShader72,"des_facmetalsolid")
engineApplyShaderToWorldTexture(texShader72,"ws_goldengate5bnoalpha")
engineApplyShaderToWorldTexture(texShader72,"lodgoldengate5bnoalpha")

texShader73 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/73.png")
dxSetShaderValue(texShader73,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader73,"ws_alley_conc3")
engineApplyShaderToWorldTexture(texShader73,"lodeyfuckingway_sfs")

texShader74 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/74.png")
dxSetShaderValue(texShader74,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader74,"hedge2lod")
engineApplyShaderToWorldTexture(texShader74,"lod_hedge1_256")
engineApplyShaderToWorldTexture(texShader74,"veg_hedge1_lod")
engineApplyShaderToWorldTexture(texShader74,"veg_hedge1_256")
engineApplyShaderToWorldTexture(texShader74,"newhedgea")
engineApplyShaderToWorldTexture(texShader74,"hedge2_256")
engineApplyShaderToWorldTexture(texShader74,"golf_hedge1")
engineApplyShaderToWorldTexture(texShader74,"hedge1")
engineApplyShaderToWorldTexture(texShader74,"ws_woodyhedge")
engineApplyShaderToWorldTexture(texShader74,"hedge1_law")
engineApplyShaderToWorldTexture(texShader74,"hedgealphad1")
engineApplyShaderToWorldTexture(texShader74,"hedge2")
engineApplyShaderToWorldTexture(texShader74,"aamanbev96x")
engineApplyShaderToWorldTexture(texShader74,"newhedgea_lod")
engineApplyShaderToWorldTexture(texShader74,"dryhedge_128")

texShader75 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/75.png")
dxSetShaderValue(texShader75,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader75,"cj_napkin")

texShader76 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/76.png")
dxSetShaderValue(texShader76,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader76,"waterclear256")

texShader77 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/77.png")
dxSetShaderValue(texShader77,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader77,"cloudmasked")

texShader78 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/78.png")
dxSetShaderValue(texShader78,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader78,"sm_des_bush1")

texShader79 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/79.png")
dxSetShaderValue(texShader79,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader79,"gras07si")
engineApplyShaderToWorldTexture(texShader79,"oak2b")
engineApplyShaderToWorldTexture(texShader79,"starflower1")

texShader80 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/80.png")
dxSetShaderValue(texShader80,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader80,"newtreed256")
engineApplyShaderToWorldTexture(texShader80,"veg_bush2")

texShader81 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/81.png")
dxSetShaderValue(texShader81,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader81,"sm_agave_bloom")
engineApplyShaderToWorldTexture(texShader81,"deadpalm01")
engineApplyShaderToWorldTexture(texShader81,"dead_fuzzy")
engineApplyShaderToWorldTexture(texShader81,"plantb256")
engineApplyShaderToWorldTexture(texShader81,"kbplanter_plants1")
engineApplyShaderToWorldTexture(texShader81,"planta256")
engineApplyShaderToWorldTexture(texShader81,"sm_minipalm1")
engineApplyShaderToWorldTexture(texShader81,"yuka256")
engineApplyShaderToWorldTexture(texShader81,"bush_med08")

texShader82 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/82.png")
dxSetShaderValue(texShader82,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader82,"starflower2")

texShader83 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/83.png")
dxSetShaderValue(texShader83,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader83,"sm_des_bush2")
engineApplyShaderToWorldTexture(texShader83,"sm_josh_leaf")

texShader84 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/84.png")
dxSetShaderValue(texShader84,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader84,"telewireslong2")
engineApplyShaderToWorldTexture(texShader84,"telewireslong")

texShader85 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/85.png")
dxSetShaderValue(texShader85,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader85,"txgrass0_1")
engineApplyShaderToWorldTexture(texShader85,"txgrass1_1")
engineApplyShaderToWorldTexture(texShader85,"txgrass1_0")
engineApplyShaderToWorldTexture(texShader85,"starflower4")
engineApplyShaderToWorldTexture(texShader85,"starflower3")
engineApplyShaderToWorldTexture(texShader85,"txgrass0_1")

texShader86 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/86.png")
dxSetShaderValue(texShader86,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader86,"aztecas")

texShader87 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/87.png")
dxSetShaderValue(texShader87,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader87,"vagos")

texShader88 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/88.png")
dxSetShaderValue(texShader88,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader88,"kilotray")

texShader89 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/89.png")
dxSetShaderValue(texShader89,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader89,"temple")

texShader90 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/90.png")
dxSetShaderValue(texShader90,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader90,"frontyard")

texShader91 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/91.png")
dxSetShaderValue(texShader91,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader91,"rollin")

texShader92 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/92.png")
dxSetShaderValue(texShader92,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader92,"rifa")

texShader93 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/93.png")
dxSetShaderValue(texShader93,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader93,"seville")

texShader94 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/94.png")
dxSetShaderValue(texShader94,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader94,"leather_seat_256")
engineApplyShaderToWorldTexture(texShader94,"win_desktop")
engineApplyShaderToWorldTexture(texShader94,"sl_dtwinlights1")
engineApplyShaderToWorldTexture(texShader94,"sl_dtwinlights2")
engineApplyShaderToWorldTexture(texShader94,"sl_dtwinlights3")
engineApplyShaderToWorldTexture(texShader94,"nitwin01_la")
engineApplyShaderToWorldTexture(texShader94,"sfnitewindows")
engineApplyShaderToWorldTexture(texShader94,"monlith_win_tex")
engineApplyShaderToWorldTexture(texShader94,"vgsn_nl_strip")
engineApplyShaderToWorldTexture(texShader94,"ws_boxhouse_wins6nite")
engineApplyShaderToWorldTexture(texShader94,"vinewood2lod")
engineApplyShaderToWorldTexture(texShader94,"font2")
engineApplyShaderToWorldTexture(texShader94,"shad_exp")
engineApplyShaderToWorldTexture(texShader94,"des_bunting")
engineApplyShaderToWorldTexture(texShader94,"grove")
engineApplyShaderToWorldTexture(texShader94,"clothline1_lae")
engineApplyShaderToWorldTexture(texShader94,"sm_cactus_leaf")
engineApplyShaderToWorldTexture(texShader94,"cs_rockdetail")
engineApplyShaderToWorldTexture(texShader94,"grille2_la")
engineApplyShaderToWorldTexture(texShader94,"graffiti")
engineApplyShaderToWorldTexture(texShader94,"wctitle")
engineApplyShaderToWorldTexture(texShader94,"lod_redwoodgrp")
engineApplyShaderToWorldTexture(texShader94,"lod_largefurs07")
engineApplyShaderToWorldTexture(texShader94,"veg_largefurs06")
engineApplyShaderToWorldTexture(texShader94,"veg_largefurs05")
engineApplyShaderToWorldTexture(texShader94,"mp_torenoshada")
engineApplyShaderToWorldTexture(texShader94,"emerald_block")
engineApplyShaderToWorldTexture(texShader94,"des_rockyfill")
engineApplyShaderToWorldTexture(texShader94,"muddywater")
engineApplyShaderToWorldTexture(texShader94,"handman")
engineApplyShaderToWorldTexture(texShader94,"coronastar")
engineApplyShaderToWorldTexture(texShader94,"shad_exp")
engineApplyShaderToWorldTexture(texShader94,"lvswelvomesign02")
engineApplyShaderToWorldTexture(texShader94,"ivy4new")

texShader95 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/95.png")
dxSetShaderValue(texShader95,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader95,"txgrass1_3")
engineApplyShaderToWorldTexture(texShader95,"fuzzyplant256")
engineApplyShaderToWorldTexture(texShader95,"plantc256")
engineApplyShaderToWorldTexture(texShader95,"newtreeleavesb128")
engineApplyShaderToWorldTexture(texShader95,"sm_agave_2")

texShader96 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/96.png")
dxSetShaderValue(texShader96,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader96,"starhedge2")

texShader97 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/97.png")
dxSetShaderValue(texShader97,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader97,"newtreeleaves128")

texShader98 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/98.png")
dxSetShaderValue(texShader98,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader98,"foliage256")

texShader99 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/99.png")
dxSetShaderValue(texShader99,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader99,"berrybush1")
engineApplyShaderToWorldTexture(texShader99,"veg_bush4")

texShader100 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/100.png")
dxSetShaderValue(texShader100,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader100,"veg_bush1")

texShader101 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/101.png")
dxSetShaderValue(texShader101,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader101,"kb_balcony_ferns")
engineApplyShaderToWorldTexture(texShader101,"kb_ivy2_256")

texShader102 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/102.png")
dxSetShaderValue(texShader102,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader102,"forestfloorblendded")


texShader103 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/103.png")
dxSetShaderValue(texShader103,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader103,"sm_des_bush3")

texShader104 = dxCreateShader ( "shader/texreplace.fx" )

Shader = dxCreateTexture("generic/104.png")
dxSetShaderValue(texShader104,"gTexture",Shader)
engineApplyShaderToWorldTexture(texShader104,"veg_bushred")
engineApplyShaderToWorldTexture(texShader104,"veg_leaf")
engineApplyShaderToWorldTexture(texShader104,"sm_agave_1")
engineApplyShaderToWorldTexture(texShader104,"dead_agave")



































