local handlingi = {

   [411] = function(car)
   setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 290)
        setVehicleHandling(car, "engineAcceleration", 35)
        setVehicleHandling(car, "engineInertia", 35)
        setVehicleHandling(car, "driveType","RWD")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 55)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.5)
        setVehicleHandling(car, "mass", 1900)
        setVehicleHandling(car, "turnMass",2725 )
        setVehicleHandling(car, "dragCoeff",1.5 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.0,-0.2} )
        setVehicleHandling(car, "percentSubmerged",70 )
        setVehicleHandling(car, "seatOffsetDistance", 1)
        setVehicleHandling(car, "tractionMultiplier",1.5 )
        setVehicleHandling(car, "tractionLoss",1.4)
        setVehicleHandling(car, "tractionBias", 0.4)
        setVehicleHandling(car, "brakeDeceleration", 8)
        setVehicleHandling(car, "brakeBias", 0.51)
        setVehicleHandling(car, "suspensionForceLevel", 1.2)
        setVehicleHandling(car, "suspensionDamping", 0.19)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0.2)
        setVehicleHandling(car, "suspensionUpperLimit", 0.25)
        setVehicleHandling(car, "suspensionLowerLimit", -0.1)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.4)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end,
	[558] = function(car)
		setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 290)
        setVehicleHandling(car, "engineAcceleration", 27)
        setVehicleHandling(car, "engineInertia", 27)
        setVehicleHandling(car, "driveType","RWD")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 45)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.5)
        setVehicleHandling(car, "mass", 1900)
        setVehicleHandling(car, "turnMass",2725 )
        setVehicleHandling(car, "dragCoeff",1.5 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.0,-0.2} )
        setVehicleHandling(car, "percentSubmerged",70 )
        setVehicleHandling(car, "seatOffsetDistance", 1)
        setVehicleHandling(car, "tractionMultiplier",1.5 )
        setVehicleHandling(car, "tractionLoss",1.4)
        setVehicleHandling(car, "tractionBias", 0.4)
        setVehicleHandling(car, "brakeDeceleration", 8)
        setVehicleHandling(car, "brakeBias", 0.51)
        setVehicleHandling(car, "suspensionForceLevel", 1.2)
        setVehicleHandling(car, "suspensionDamping", 0.19)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0.2)
        setVehicleHandling(car, "suspensionUpperLimit", 0.25)
        setVehicleHandling(car, "suspensionLowerLimit", -0.1)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.4)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end,
	[559] = function(car) -- jester
		setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 190)
        setVehicleHandling(car, "engineAcceleration", 15)
        setVehicleHandling(car, "engineInertia", 10)
        setVehicleHandling(car, "driveType","FWD")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 30)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.6)
        setVehicleHandling(car, "mass", 1500)
        setVehicleHandling(car, "turnMass", 3600)
        setVehicleHandling(car, "dragCoeff",2.2 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.0,-0.05} )
        setVehicleHandling(car, "percentSubmerged",75 )
        setVehicleHandling(car, "seatOffsetDistance", 0.25)
        setVehicleHandling(car, "tractionMultiplier",1.1 )
        setVehicleHandling(car, "tractionLoss",0.8)
        setVehicleHandling(car, "tractionBias", 0.5)
        setVehicleHandling(car, "brakeDeceleration",10 )
        setVehicleHandling(car, "brakeBias", 0.45)
        setVehicleHandling(car, "suspensionForceLevel", 1.1)
        setVehicleHandling(car, "suspensionDamping", 0.1)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.28)
        setVehicleHandling(car, "suspensionLowerLimit", -0.15)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.3)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end, 
	[596] = function(car)
		setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 190)
        setVehicleHandling(car, "engineAcceleration", 14)
        setVehicleHandling(car, "engineInertia", 10)
        setVehicleHandling(car, "driveType","RWD")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 45)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.22)
        setVehicleHandling(car, "mass", 1600)
        setVehicleHandling(car, "turnMass", 4500)
        setVehicleHandling(car, "dragCoeff",2 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.3,-0.1} )
        setVehicleHandling(car, "percentSubmerged",75 )
        setVehicleHandling(car, "seatOffsetDistance", 0.2)
        setVehicleHandling(car, "tractionMultiplier",0.95 )
        setVehicleHandling(car, "tractionLoss",0.85)
        setVehicleHandling(car, "tractionBias", 0.5)
        setVehicleHandling(car, "brakeDeceleration",10 )
        setVehicleHandling(car, "brakeBias", 0.53)
        setVehicleHandling(car, "suspensionForceLevel", 1)
        setVehicleHandling(car, "suspensionDamping", 0.12)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.28)
        setVehicleHandling(car, "suspensionLowerLimit", -0.12)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.55)
    end,
    [451] = function(car)
        setVehicleHandling(car, "numberOfGears", 5)
		setVehicleHandling(car, "maxVelocity", 350)
        setVehicleHandling(car, "engineAcceleration", 22)
        setVehicleHandling(car, "engineInertia", 10)
        setVehicleHandling(car, "driveType","RWD")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 45)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.5)
        setVehicleHandling(car, "mass", 1400)
        setVehicleHandling(car, "turnMass",1700 )
        setVehicleHandling(car, "dragCoeff",1.5 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.0,-0.2} )
        setVehicleHandling(car, "percentSubmerged",70 )
        setVehicleHandling(car, "seatOffsetDistance", 0.4)
        setVehicleHandling(car, "tractionMultiplier",1 )
        setVehicleHandling(car, "tractionLoss",1)
        setVehicleHandling(car, "tractionBias", 0.5)
        setVehicleHandling(car, "brakeDeceleration", 30)
        setVehicleHandling(car, "brakeBias", 0.51)
        setVehicleHandling(car, "suspensionForceLevel", 2)
        setVehicleHandling(car, "suspensionDamping", 0.19)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.5)
        setVehicleHandling(car, "suspensionLowerLimit", -0.1)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.4)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)

    end,	
	[429] = function(car)
		setVehicleHandling(car, "numberOfGears", 5)
		setVehicleHandling(car, "maxVelocity", 210)
        setVehicleHandling(car, "engineAcceleration", 16)
        setVehicleHandling(car, "engineInertia", 10)
        setVehicleHandling(car, "driveType","RWD")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 34)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.35)
        setVehicleHandling(car, "mass", 1400)
        setVehicleHandling(car, "turnMass",3000 )
        setVehicleHandling(car, "dragCoeff",2 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.0,-0.2} )
        setVehicleHandling(car, "percentSubmerged",70 )
        setVehicleHandling(car, "seatOffsetDistance", 0.15)
        setVehicleHandling(car, "tractionMultiplier",1 )
        setVehicleHandling(car, "tractionLoss",0.89)
        setVehicleHandling(car, "tractionBias", 0.5)
        setVehicleHandling(car, "brakeDeceleration",8)
        setVehicleHandling(car, "brakeBias", 0.52)
        setVehicleHandling(car, "suspensionForceLevel", 1.6)
        setVehicleHandling(car, "suspensionDamping", 0.1)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 5)
        setVehicleHandling(car, "suspensionUpperLimit", 0.3)
        setVehicleHandling(car, "suspensionLowerLimit", -0.15)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.3)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end,	
    [541] = function(car)
	setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 255)
        setVehicleHandling(car, "engineAcceleration", 23.7)
        setVehicleHandling(car, "engineInertia", 10)
        setVehicleHandling(car, "driveType","RWD")
        setVehicleHandling(car, "engineType", "diesel")
        setVehicleHandling(car, "steeringLock", 40)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.45)
        setVehicleHandling(car, "mass", 2000)
        setVehicleHandling(car, "turnMass",3000 )
        setVehicleHandling(car, "dragCoeff",2 )
        setVehicleHandling(car, "centerOfMass", {0.0,-0.15,-0.2} )
        setVehicleHandling(car, "percentSubmerged",71 )
        setVehicleHandling(car, "seatOffsetDistance", 0.15)
        setVehicleHandling(car, "tractionMultiplier",1.1)
        setVehicleHandling(car, "tractionLoss",1.1)
        setVehicleHandling(car, "tractionBias", 0.45)
        setVehicleHandling(car, "brakeDeceleration",10)
        setVehicleHandling(car, "brakeBias", 0.52)
        setVehicleHandling(car, "suspensionForceLevel", 1)
        setVehicleHandling(car, "suspensionDamping", 1)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 5)
        setVehicleHandling(car, "suspensionUpperLimit", 0.25)
        setVehicleHandling(car, "suspensionLowerLimit", -0.1)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.3)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.45)
    end,
    [415] = function(car)
		setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 255)
        setVehicleHandling(car, "engineAcceleration", 20)
        setVehicleHandling(car, "engineInertia", -100)
        setVehicleHandling(car, "driveType","RWD")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 35)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.45)
        setVehicleHandling(car, "mass", 1200)
        setVehicleHandling(car, "turnMass",3000 )
        setVehicleHandling(car, "dragCoeff",2 )
        setVehicleHandling(car, "centerOfMass", {0.0,-0.2,-0.2} )
        setVehicleHandling(car, "percentSubmerged",70 )
        setVehicleHandling(car, "seatOffsetDistance", 0.4)
        setVehicleHandling(car, "tractionMultiplier",0.9 )
        setVehicleHandling(car, "tractionLoss",0.9)
        setVehicleHandling(car, "tractionBias", 0.5)
        setVehicleHandling(car, "brakeDeceleration", 11.1)
        setVehicleHandling(car, "brakeBias", 0.48)
        setVehicleHandling(car, "suspensionForceLevel", 0.8)
        setVehicleHandling(car, "suspensionDamping", 0.2)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.1)
        setVehicleHandling(car, "suspensionLowerLimit", -0.15)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.6)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end,
    [495] = function(car)
		setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 220)
        setVehicleHandling(car, "engineAcceleration", 23)
        setVehicleHandling(car, "engineInertia", 15)
        setVehicleHandling(car, "driveType","AWD")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 43)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.30)
        setVehicleHandling(car, "mass", 2000)
        setVehicleHandling(car, "turnMass",4000)
        setVehicleHandling(car, "dragCoeff",2.2 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.0,-0.6} )
        setVehicleHandling(car, "percentSubmerged",80 )
        setVehicleHandling(car, "seatOffsetDistance", 0.38)
        setVehicleHandling(car, "tractionMultiplier",1.1 )
        setVehicleHandling(car, "tractionLoss",0.85)
        setVehicleHandling(car, "tractionBias", 0.5)
        setVehicleHandling(car, "brakeDeceleration",8)
        setVehicleHandling(car, "brakeBias", 0.5)
        setVehicleHandling(car, "suspensionForceLevel", 0.8)
        setVehicleHandling(car, "suspensionDamping", 0.08)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.35)
        setVehicleHandling(car, "suspensionLowerLimit", -0.31)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end,
	[489] = function(car)
		setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 220)
        setVehicleHandling(car, "engineAcceleration", 20)
        setVehicleHandling(car, "engineInertia", 10)
        setVehicleHandling(car, "driveType","AWD")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 43)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.30)
        setVehicleHandling(car, "mass", 2000)
        setVehicleHandling(car, "turnMass",4000)
        setVehicleHandling(car, "dragCoeff",2.2 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.0,-0.6} )
        setVehicleHandling(car, "percentSubmerged",80 )
        setVehicleHandling(car, "seatOffsetDistance", 0.38)
        setVehicleHandling(car, "tractionMultiplier",1.1 )
        setVehicleHandling(car, "tractionLoss",0.85)
        setVehicleHandling(car, "tractionBias", 0.5)
        setVehicleHandling(car, "brakeDeceleration",8)
        setVehicleHandling(car, "brakeBias", 0.5)
        setVehicleHandling(car, "suspensionForceLevel", 0.8)
        setVehicleHandling(car, "suspensionDamping", 0.08)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.35)
        setVehicleHandling(car, "suspensionLowerLimit", -0.31)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end,
    [400] = function(car)
		setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 180)
        setVehicleHandling(car, "engineAcceleration", 15)
        setVehicleHandling(car, "engineInertia", 5)
        setVehicleHandling(car, "driveType","AWD")
        setVehicleHandling(car, "engineType", "diesel")
        setVehicleHandling(car, "steeringLock", 40)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.26)
        setVehicleHandling(car, "mass", 2700)
        setVehicleHandling(car, "turnMass", 4500)
        setVehicleHandling(car, "dragCoeff",2.5 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.0,-0.3} )
        setVehicleHandling(car, "percentSubmerged",70 )
        setVehicleHandling(car, "seatOffsetDistance", 0.27)
        setVehicleHandling(car, "tractionMultiplier",0.9 )
        setVehicleHandling(car, "tractionLoss",1)
        setVehicleHandling(car, "tractionBias", 0.6)
        setVehicleHandling(car, "brakeDeceleration",7000 )
        setVehicleHandling(car, "brakeBias", 0.6)
        setVehicleHandling(car, "suspensionForceLevel", 0.6)
        setVehicleHandling(car, "suspensionDamping", 0.1)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0.1)
        setVehicleHandling(car, "suspensionUpperLimit", 0.28)
        setVehicleHandling(car, "suspensionLowerLimit", -0.14)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.25)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end,
	[579] = function(car)
		setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 200)
        setVehicleHandling(car, "engineAcceleration", 18,5)
        setVehicleHandling(car, "engineInertia", 10)
        setVehicleHandling(car, "driveType","AWD")
        setVehicleHandling(car, "engineType", "diesel")
        setVehicleHandling(car, "steeringLock", 40)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.3)
        setVehicleHandling(car, "mass", 3000)
        setVehicleHandling(car, "turnMass", 4000)
        setVehicleHandling(car, "dragCoeff",2 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.0,-0.2} )
        setVehicleHandling(car, "percentSubmerged",80 )
        setVehicleHandling(car, "seatOffsetDistance", 0.44)
        setVehicleHandling(car, "tractionMultiplier",0.8 )
        setVehicleHandling(car, "tractionLoss",0.75)
        setVehicleHandling(car, "tractionBias", 0.5)
        setVehicleHandling(car, "brakeDeceleration",50 )
        setVehicleHandling(car, "brakeBias", 0.5)
        setVehicleHandling(car, "suspensionForceLevel", 1)
        setVehicleHandling(car, "suspensionDamping", 0.05)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.45)
        setVehicleHandling(car, "suspensionLowerLimit", -0.21)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.3)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.45)
    end,
	[560] = function(car)
			setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 260)
        setVehicleHandling(car, "engineAcceleration", 19)
        setVehicleHandling(car, "engineInertia", 5)
        setVehicleHandling(car, "driveType","AWD")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 40)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.45)
        setVehicleHandling(car, "mass", 2200)
        setVehicleHandling(car, "turnMass", 3600)
        setVehicleHandling(car, "dragCoeff",2.4 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.1,-0.1} )
        setVehicleHandling(car, "percentSubmerged",75 )
        setVehicleHandling(car, "seatOffsetDistance", 0.25)
        setVehicleHandling(car, "tractionMultiplier",0.85 )
        setVehicleHandling(car, "tractionLoss",1)
        setVehicleHandling(car, "tractionBias", 0.5)
        setVehicleHandling(car, "brakeDeceleration",4000 )
        setVehicleHandling(car, "brakeBias", 0.6)
        setVehicleHandling(car, "suspensionForceLevel", 1.2)
        setVehicleHandling(car, "suspensionDamping", 0.15)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.28)
        setVehicleHandling(car, "suspensionLowerLimit", -0.2)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.3)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end,
    [402] = function(car)
		setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 210)
        setVehicleHandling(car, "engineAcceleration", 17)
        setVehicleHandling(car, "engineInertia", 10)
        setVehicleHandling(car, "driveType","AWD")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 40)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.5)
        setVehicleHandling(car, "mass", 2000)
        setVehicleHandling(car, "turnMass", 2600)
        setVehicleHandling(car, "dragCoeff",2 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.0,-0.1} )
        setVehicleHandling(car, "percentSubmerged",85 )
        setVehicleHandling(car, "seatOffsetDistance", 0.25)
        setVehicleHandling(car, "tractionMultiplier",1 )
        setVehicleHandling(car, "tractionLoss",0.95)
        setVehicleHandling(car, "tractionBias", 0.5)
        setVehicleHandling(car, "brakeDeceleration",11 )
        setVehicleHandling(car, "brakeBias", 0.45)
        setVehicleHandling(car, "suspensionForceLevel", 1.2)
        setVehicleHandling(car, "suspensionDamping", 0.12)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.28)
        setVehicleHandling(car, "suspensionLowerLimit", -0.24)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.4)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
end,
    [562] = function(car)
		setVehicleHandling(car, "driveType", "RWD")
		setVehicleHandling(car, "maxVelocity", 255)
		setVehicleHandling(car, "steeringLock", 32)
		setVehicleHandling(car, "engineAcceleration", 15)
		setVehicleHandling(car, "tractionMultiplier", 0.8)
		setVehicleHandling(car, "tractionLoss", 0.9)
    end, 
	[437] = function(car)
		setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 160)
        setVehicleHandling(car, "engineAcceleration", 7.2)
        setVehicleHandling(car, "engineInertia", 10)
        setVehicleHandling(car, "driveType","RWD")
        setVehicleHandling(car, "engineType", "diesel")
        setVehicleHandling(car, "steeringLock", 30)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.48)
        setVehicleHandling(car, "mass", 9500)
        setVehicleHandling(car, "turnMass",57324.602 )
        setVehicleHandling(car, "dragCoeff",1.8 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.0,0.0} )
        setVehicleHandling(car, "percentSubmerged",90 )
        setVehicleHandling(car, "seatOffsetDistance", 0.45)
        setVehicleHandling(car, "tractionMultiplier",0.65 )
        setVehicleHandling(car, "tractionLoss",0.85)
        setVehicleHandling(car, "tractionBias", 0.35)
        setVehicleHandling(car, "brakeDeceleration", 5.7)
        setVehicleHandling(car, "brakeBias", 0.35)
        setVehicleHandling(car, "suspensionForceLevel", 1.5)
        setVehicleHandling(car, "suspensionDamping", 0.04)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.45)
        setVehicleHandling(car, "suspensionLowerLimit", -0.25)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end, 
	[433] = function(car)
		setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 160)
        setVehicleHandling(car, "engineAcceleration", 15.5)
        setVehicleHandling(car, "engineInertia", 25)
        setVehicleHandling(car, "driveType","AWD")
        setVehicleHandling(car, "engineType", "diesel")
        setVehicleHandling(car, "steeringLock", 27)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.26)
        setVehicleHandling(car, "mass", 10500)
        setVehicleHandling(car, "turnMass",61407.5 )
        setVehicleHandling(car, "dragCoeff",4 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.0,0.0} )
        setVehicleHandling(car, "percentSubmerged",90 )
        setVehicleHandling(car, "seatOffsetDistance", 0.62)
        setVehicleHandling(car, "tractionMultiplier",0.65 )
        setVehicleHandling(car, "tractionLoss",0.7)
        setVehicleHandling(car, "tractionBias", 0.47)
        setVehicleHandling(car, "brakeDeceleration", 4)
        setVehicleHandling(car, "brakeBias", 0.4)
        setVehicleHandling(car, "suspensionForceLevel", 1.2)
        setVehicleHandling(car, "suspensionDamping", 0.05)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.47)
        setVehicleHandling(car, "suspensionLowerLimit", -0.17)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end, 
	[470] = function(car)
		setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 220)
        setVehicleHandling(car, "engineAcceleration", 20)
        setVehicleHandling(car, "engineInertia", 20)
        setVehicleHandling(car, "driveType","AWD")
        setVehicleHandling(car, "engineType", "diesel")
        setVehicleHandling(car, "steeringLock", 40)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.125)
        setVehicleHandling(car, "mass", 4000)
        setVehicleHandling(car, "turnMass",7000 )
        setVehicleHandling(car, "dragCoeff",2 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.0,0.0} )
        setVehicleHandling(car, "percentSubmerged",80 )
        setVehicleHandling(car, "seatOffsetDistance", 0.28)
        setVehicleHandling(car, "tractionMultiplier",0.8 )
        setVehicleHandling(car, "tractionLoss",0.9)
        setVehicleHandling(car, "tractionBias", 0.5)
        setVehicleHandling(car, "brakeDeceleration", 8)
        setVehicleHandling(car, "brakeBias", 0.5)
        setVehicleHandling(car, "suspensionForceLevel", 0.9)
        setVehicleHandling(car, "suspensionDamping", 1)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 4)
        setVehicleHandling(car, "suspensionUpperLimit", 0.35)
        setVehicleHandling(car, "suspensionLowerLimit", -0.35)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end, 
    [522] = function(car)
		setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 250)
        setVehicleHandling(car, "engineAcceleration", 30)
        setVehicleHandling(car, "engineInertia", 5)
        setVehicleHandling(car, "driveType","RWD")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 35)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.15)
        setVehicleHandling(car, "mass", 400)
        setVehicleHandling(car, "turnMass",200)
        setVehicleHandling(car, "dragCoeff",4 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.08,-0.09} )
        setVehicleHandling(car, "percentSubmerged",103 )
        setVehicleHandling(car, "seatOffsetDistance", 0)
        setVehicleHandling(car, "tractionMultiplier",1.8 )
        setVehicleHandling(car, "tractionLoss",0.9)
        setVehicleHandling(car, "tractionBias", 0.48)
        setVehicleHandling(car, "brakeDeceleration",15 )
        setVehicleHandling(car, "brakeBias", 0.5)
        setVehicleHandling(car, "suspensionForceLevel", 0.85)
        setVehicleHandling(car, "suspensionDamping", 0.15)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.15)
        setVehicleHandling(car, "suspensionLowerLimit", -0.16)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end,
	[551] = function(car)
		setVehicleHandling(car, "numberOfGears", 3)
        setVehicleHandling(car, "maxVelocity", 200)
        setVehicleHandling(car, "engineAcceleration", 14.5)
        setVehicleHandling(car, "engineInertia", -10)
        setVehicleHandling(car, "driveType","RWD")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 47)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.56)
        setVehicleHandling(car, "mass", 1800)
        setVehicleHandling(car, "turnMass",4500)
        setVehicleHandling(car, "dragCoeff",2.2 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.2,-0.1} )
        setVehicleHandling(car, "percentSubmerged",75 )
        setVehicleHandling(car, "seatOffsetDistance", 0.2)
        setVehicleHandling(car, "tractionMultiplier",0.9 )
        setVehicleHandling(car, "tractionLoss",1)
        setVehicleHandling(car, "tractionBias", 0.49)
        setVehicleHandling(car, "brakeDeceleration",9 )
        setVehicleHandling(car, "brakeBias", 0.55)
        setVehicleHandling(car, "suspensionForceLevel", 1.1)
        setVehicleHandling(car, "suspensionDamping", 0.15)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.27)
        setVehicleHandling(car, "suspensionLowerLimit", -0.08)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.3)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.54)
    end,
	[507] = function(car)
		setVehicleHandling(car, "numberOfGears", 4)
        setVehicleHandling(car, "maxVelocity", 280)
        setVehicleHandling(car, "engineAcceleration", 18.5)
        setVehicleHandling(car, "engineInertia", 17.5)
        setVehicleHandling(car, "driveType","awd")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 30)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.45)
        setVehicleHandling(car, "mass", 2200)
        setVehicleHandling(car, "turnMass",5000)
        setVehicleHandling(car, "dragCoeff",1.45 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.1,-0.1} )
        setVehicleHandling(car, "percentSubmerged",75 )
        setVehicleHandling(car, "seatOffsetDistance", 0.2)
        setVehicleHandling(car, "tractionMultiplier",0.8 )
        setVehicleHandling(car, "tractionLoss",0.8)
        setVehicleHandling(car, "tractionBias", 0.46)
        setVehicleHandling(car, "brakeDeceleration",6 )
        setVehicleHandling(car, "brakeBias", 0.55)
        setVehicleHandling(car, "suspensionForceLevel", 1)
        setVehicleHandling(car, "suspensionDamping", 0.1)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.35)
        setVehicleHandling(car, "suspensionLowerLimit", -0.15)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.3)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end,
	[475] = function(car)
		setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 220)
        setVehicleHandling(car, "engineAcceleration", 18)
        setVehicleHandling(car, "engineInertia", 20)
        setVehicleHandling(car, "driveType","RWD")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 40)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.43)
        setVehicleHandling(car, "mass", 1600)
        setVehicleHandling(car, "turnMass",3000)
        setVehicleHandling(car, "dragCoeff",1.4 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.2,-0.4} )
        setVehicleHandling(car, "percentSubmerged",70 )
        setVehicleHandling(car, "seatOffsetDistance", 0.25)
        setVehicleHandling(car, "tractionMultiplier",1.1 )
        setVehicleHandling(car, "tractionLoss",0.8)
        setVehicleHandling(car, "tractionBias", 0.53)
        setVehicleHandling(car, "brakeDeceleration",8 )
        setVehicleHandling(car, "brakeBias", 0.52)
        setVehicleHandling(car, "suspensionForceLevel", 1.5)
        setVehicleHandling(car, "suspensionDamping", 0.5)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 5)
        setVehicleHandling(car, "suspensionUpperLimit", 0.3)
        setVehicleHandling(car, "suspensionLowerLimit", -0.2)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.25)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end,
	[496] = function(car)
		setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 170)
        setVehicleHandling(car, "engineAcceleration", 11)
        setVehicleHandling(car, "engineInertia", 5)
        setVehicleHandling(car, "driveType","FWD")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 30)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.5)
        setVehicleHandling(car, "mass", 1000)
        setVehicleHandling(car, "turnMass",2100)
        setVehicleHandling(car, "dragCoeff",2.4 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.0,-0.1} )
        setVehicleHandling(car, "percentSubmerged",50 )
        setVehicleHandling(car, "seatOffsetDistance", 0.25)
        setVehicleHandling(car, "tractionMultiplier",0.85 )
        setVehicleHandling(car, "tractionLoss",0.85)
        setVehicleHandling(car, "tractionBias", 0.5)
        setVehicleHandling(car, "brakeDeceleration",11 )
        setVehicleHandling(car, "brakeBias", 0.45)
        setVehicleHandling(car, "suspensionForceLevel", 1.4)
        setVehicleHandling(car, "suspensionDamping", 0.1)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.28)
        setVehicleHandling(car, "suspensionLowerLimit", -0.3)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end,
[565] = function(car)
        setVehicleHandling(car, "driveType",'awd')
        setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 220)
        setVehicleHandling(car, "engineAcceleration", 17)
        setVehicleHandling(car, "engineInertia", 10)
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 35)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.45)
        setVehicleHandling(car, "mass", 1600)
        setVehicleHandling(car, "turnMass", 3000)
        setVehicleHandling(car, "dragCoeff",2.2 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.2,-0.1} )
        setVehicleHandling(car, "percentSubmerged",70 )
        setVehicleHandling(car, "seatOffsetDistance", 1)
        setVehicleHandling(car, "tractionMultiplier",1.5 )
        setVehicleHandling(car, "tractionLoss",0.9)
        setVehicleHandling(car, "tractionBias", 0.5)
        setVehicleHandling(car, "brakeDeceleration",8 )
        setVehicleHandling(car, "brakeBias", 0)
        setVehicleHandling(car, "suspensionForceLevel", 1.4)
        setVehicleHandling(car, "suspensionDamping", 0.15)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.28)
        setVehicleHandling(car, "suspensionLowerLimit", -0.1)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.3)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
end,
	[506] = function(car)
		setVehicleHandling(car, "driveType",'awd')
		setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 210)
        setVehicleHandling(car, "engineAcceleration", 16)
        setVehicleHandling(car, "engineInertia", 10)
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 40)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.45)
        setVehicleHandling(car, "mass", 1400)
        setVehicleHandling(car, "turnMass", 2700)
        setVehicleHandling(car, "dragCoeff",2 )
        setVehicleHandling(car, "centerOfMass", {0.0,-0.2,-0.24} )
        setVehicleHandling(car, "percentSubmerged",70 )
        setVehicleHandling(car, "seatOffsetDistance", 0.4)
        setVehicleHandling(car, "tractionMultiplier",1 )
        setVehicleHandling(car, "tractionLoss",1.25)
        setVehicleHandling(car, "tractionBias", 0.5)
        setVehicleHandling(car, "brakeDeceleration",8 )
        setVehicleHandling(car, "brakeBias", 0.52)
        setVehicleHandling(car, "suspensionForceLevel", 1)
        setVehicleHandling(car, "suspensionDamping", 0.2)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.25)
        setVehicleHandling(car, "suspensionLowerLimit", -0.1)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.3)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end,
	[601] = function(car)
		setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 150)
        setVehicleHandling(car, "engineAcceleration", 16)
        setVehicleHandling(car, "engineInertia", 25)
        setVehicleHandling(car, "driveType","AWD")
        setVehicleHandling(car, "engineType", "diesel")
        setVehicleHandling(car, "steeringLock", 35)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.06)
        setVehicleHandling(car, "mass", 5000)
        setVehicleHandling(car, "turnMass", 10000)
        setVehicleHandling(car, "dragCoeff",2.5 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.0,-0.1} )
        setVehicleHandling(car, "percentSubmerged",85 )
        setVehicleHandling(car, "seatOffsetDistance", 0.32)
        setVehicleHandling(car, "tractionMultiplier",0.8 )
        setVehicleHandling(car, "tractionLoss",0.7)
        setVehicleHandling(car, "tractionBias", 0.46)
        setVehicleHandling(car, "brakeDeceleration",6.4 )
        setVehicleHandling(car, "brakeBias", 0.45)
        setVehicleHandling(car, "suspensionForceLevel", 0.7)
        setVehicleHandling(car, "suspensionDamping", 0.08)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 1)
        setVehicleHandling(car, "suspensionUpperLimit", 0.3)
        setVehicleHandling(car, "suspensionLowerLimit", -0.18)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end,
	[550] = function(car)
		setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 190)
        setVehicleHandling(car, "engineAcceleration", 7)
        setVehicleHandling(car, "engineInertia", 5)
        setVehicleHandling(car, "driveType","FWD")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 30)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.54)
        setVehicleHandling(car, "mass", 1600)
        setVehicleHandling(car, "turnMass", 3550)
        setVehicleHandling(car, "dragCoeff",2 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.3,0.0} )
        setVehicleHandling(car, "percentSubmerged",70 )
        setVehicleHandling(car, "seatOffsetDistance", 0.26)
        setVehicleHandling(car, "tractionMultiplier",1 )
        setVehicleHandling(car, "tractionLoss",0.8)
        setVehicleHandling(car, "tractionBias", 0.52)
        setVehicleHandling(car, "brakeDeceleration",9005 )
        setVehicleHandling(car, "brakeBias", 0.6)
        setVehicleHandling(car, "suspensionForceLevel", 1)
        setVehicleHandling(car, "suspensionDamping", 0.09)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.3)
        setVehicleHandling(car, "suspensionLowerLimit", -0.12)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.55)
    end,
	[494] = function(car)
		setVehicleHandling(car, "numberOfGears", 4)
        setVehicleHandling(car, "maxVelocity", 310)
        setVehicleHandling(car, "engineAcceleration", 22)
        setVehicleHandling(car, "engineInertia", -1000)
        setVehicleHandling(car, "driveType","AWD")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 36)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.45)
        setVehicleHandling(car, "mass", 1600)
        setVehicleHandling(car, "turnMass", 2800)
    end,
	[503] = function(car)
	setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 325)
        setVehicleHandling(car, "engineAcceleration", 25)
        setVehicleHandling(car, "engineInertia", 5)
        setVehicleHandling(car, "driveType","awd")
        setVehicleHandling(car, "engineType", "diesel")
        setVehicleHandling(car, "steeringLock", 45)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.30)
        setVehicleHandling(car, "mass", 1600)
        setVehicleHandling(car, "turnMass", 3000)
        setVehicleHandling(car, "dragCoeff",1.4 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.2,-0.4} )
        setVehicleHandling(car, "percentSubmerged",70 )
        setVehicleHandling(car, "seatOffsetDistance", 0)
        setVehicleHandling(car, "tractionMultiplier",1.4 )
        setVehicleHandling(car, "tractionLoss",0.9)
        setVehicleHandling(car, "tractionBias", 0.5)
        setVehicleHandling(car, "brakeDeceleration",10 )
        setVehicleHandling(car, "brakeBias", 0.50)
        setVehicleHandling(car, "suspensionForceLevel", 1.7)
        setVehicleHandling(car, "suspensionDamping", 0.1)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 10)
        setVehicleHandling(car, "suspensionUpperLimit", 0.4)
        setVehicleHandling(car, "suspensionLowerLimit", -0.18)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.4)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end,
	[426] = function(car)
		setVehicleHandling(car, "mass", 1750)
        setVehicleHandling(car, "turnMass",2900 )
        setVehicleHandling(car, "dragCoeff",1.5 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.0,-0.3} )
        setVehicleHandling(car, "percentSubmerged",70 )
        setVehicleHandling(car, "tractionMultiplier",1.4 )
        setVehicleHandling(car, "tractionLoss",1)
        setVehicleHandling(car, "tractionBias", 0.5)
        setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 285)
        setVehicleHandling(car, "engineAcceleration", 35)
        setVehicleHandling(car, "engineInertia", 35)
        setVehicleHandling(car, "driveType", "awd")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "brakeDeceleration", 8)
        setVehicleHandling(car, "brakeBias", 0.51)
        setVehicleHandling(car, "steeringLock", 55)
        setVehicleHandling(car, "suspensionForceLevel", 1.2)
        setVehicleHandling(car, "suspensionDamping", 0.19)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0.2)
        setVehicleHandling(car, "suspensionUpperLimit", 0.25)
        setVehicleHandling(car, "suspensionLowerLimit", -0.1)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.4)
        setVehicleHandling(car, "seatOffsetDistance", 1)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.3) 
    end,
	[542] = function(car)
		setVehicleHandling(car, "numberOfGears", 4)
        setVehicleHandling(car, "maxVelocity", 180)
        setVehicleHandling(car, "engineAcceleration", 11.5)
        setVehicleHandling(car, "engineInertia", 10)
        setVehicleHandling(car, "driveType","RWD")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 40)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.52)
        setVehicleHandling(car, "mass", 1600)
        setVehicleHandling(car, "turnMass", 3000)
        setVehicleHandling(car, "dragCoeff",2.2 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.0,0.0} )
        setVehicleHandling(car, "percentSubmerged",70 )
        setVehicleHandling(car, "seatOffsetDistance", 0.25)
        setVehicleHandling(car, "tractionMultiplier",0.6 )
        setVehicleHandling(car, "tractionLoss",0.8)
        setVehicleHandling(car, "tractionBias", 0.52)
        setVehicleHandling(car, "brakeDeceleration",8 )
        setVehicleHandling(car, "brakeBias", 0.5)
        setVehicleHandling(car, "suspensionForceLevel", 1)
        setVehicleHandling(car, "suspensionDamping", 0.1)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.3)
        setVehicleHandling(car, "suspensionLowerLimit", -0.1)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.25)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end,
	[461] = function(car)
		setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 230)
        setVehicleHandling(car, "engineAcceleration", 30)
        setVehicleHandling(car, "engineInertia", 5)
        setVehicleHandling(car, "driveType","RWD")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "steeringLock", 35)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.15)
        setVehicleHandling(car, "mass", 500)
        setVehicleHandling(car, "turnMass", 162)
        setVehicleHandling(car, "dragCoeff",4 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.05,-0.09} )
        setVehicleHandling(car, "percentSubmerged",103 )
        setVehicleHandling(car, "seatOffsetDistance", 0)
        setVehicleHandling(car, "tractionMultiplier",1.6 )
        setVehicleHandling(car, "tractionLoss",0.9)
        setVehicleHandling(car, "tractionBias", 0.48)
        setVehicleHandling(car, "brakeDeceleration",15 )
        setVehicleHandling(car, "brakeBias", 0.5)
        setVehicleHandling(car, "suspensionForceLevel", 0.85)
        setVehicleHandling(car, "suspensionDamping", 0.15)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0)
        setVehicleHandling(car, "suspensionUpperLimit", 0.15)
        setVehicleHandling(car, "suspensionLowerLimit", -0.16)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
    end,
    [480] = function(car)
		setVehicleHandling(car, "mass", 1400)
        setVehicleHandling(car, "turnMass",2200 )
        setVehicleHandling(car, "dragCoeff",2.2 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.01,-0.02} )
        setVehicleHandling(car, "percentSubmerged",75 )
        setVehicleHandling(car, "tractionMultiplier",1 )
        setVehicleHandling(car, "tractionLoss",0.9)
        setVehicleHandling(car, "tractionBias", 0.5)
        setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 235)
        setVehicleHandling(car, "engineAcceleration", 19.5)
        setVehicleHandling(car, "engineInertia", 10)
        setVehicleHandling(car, "driveType", "awd")
        setVehicleHandling(car, "engineType", "petrol")
        setVehicleHandling(car, "brakeDeceleration", 97011)
        setVehicleHandling(car, "brakeBias", 0.45)
        setVehicleHandling(car, "steeringLock", 45)
        setVehicleHandling(car, "suspensionForceLevel", 1.4)
        setVehicleHandling(car, "suspensionDamping", 0.14)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 3)
        setVehicleHandling(car, "suspensionUpperLimit", 0.28)
        setVehicleHandling(car, "suspensionLowerLimit", -0.15)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.5)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.3)
        setVehicleHandling(car, "seatOffsetDistance", 0.25)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.6) 
	end,
	[568] = function(car)
		setVehicleHandling(car, "engineAcceleration", 25.0)
		setVehicleHandling(car, "maxVelocity", 220.0)
		setVehicleHandling(car, "driveType", "awd")
		setVehicleHandling(car, "tractionLoss", 1.5)
		setVehicleHandling(car, "brakeDeceleration", 8.0)
    end,
        [502] = function(car)
	setVehicleHandling(car, "numberOfGears", 5)
        setVehicleHandling(car, "maxVelocity", 310)
        setVehicleHandling(car, "engineAcceleration", 22)
        setVehicleHandling(car, "engineInertia", 5)
        setVehicleHandling(car, "driveType","AWD")
        setVehicleHandling(car, "engineType", "diesel")
        setVehicleHandling(car, "steeringLock", 45)
        setVehicleHandling(car, "collisionDamageMultiplier", 0.15)
        setVehicleHandling(car, "mass", 1600)
        setVehicleHandling(car, "turnMass", 2800)
        setVehicleHandling(car, "dragCoeff",1.4 )
        setVehicleHandling(car, "centerOfMass", {0.0,0.2,-0.4} )
        setVehicleHandling(car, "percentSubmerged",70 )
        setVehicleHandling(car, "seatOffsetDistance", 0.2)
        setVehicleHandling(car, "seatOffsetDistance", 0)
        setVehicleHandling(car, "tractionMultiplier",1.5 )
        setVehicleHandling(car, "tractionLoss",0.9)
        setVehicleHandling(car, "tractionBias", 0.5)
        setVehicleHandling(car, "brakeDeceleration",10 )
        setVehicleHandling(car, "brakeBias", 0.5)
        setVehicleHandling(car, "suspensionForceLevel", 3.4)
        setVehicleHandling(car, "suspensionDamping", 0.9)
        setVehicleHandling(car, "suspensionHighSpeedDamping", 0.9)
        setVehicleHandling(car, "suspensionUpperLimit", 0.29)
        setVehicleHandling(car, "suspensionLowerLimit", -0.16)
        setVehicleHandling(car, "suspensionAntiDiveMultiplier", 0.4)
        setVehicleHandling(car, "suspensionFrontRearBias", 0.6)
    end,
    


}


addEventHandler('onPlayerVehicleEnter',root,function(car)
    if handlingi[getElementModel(car)] then
        handlingi[getElementModel(car)](car)
    end
end)