local TextsTable = {
    ["ENG"] = {
    },
    ["PL"] = {
        ["Chainsaw"] = "Piła Spalinowa",
        ["Baseball Bat"] = "Kij Baseballowy",
        ["Hunting Knife"] = "Nóż Myśliwski",
        ["Sawn-Off Shotgun"] = "Dubeltówka",
        ["SPAZ-12 Combat Shotgun"] = "SPAZ-12",
        ["Spray"] = "Sprej",
        ["Parachute"] = "Spadochron",
        ["Harvest Scythe"] = "Kosa Stacha",
        ["Tear Gas"] = "Gaz Łzawiacy",
        ["Water Bottle"] = "Butelka z Wodą",
        ["Pasta Can"] = "Makaron w puszce",
        ["Beans Can"] = "Fasola w puszce",
        ["Soda Bottle"] = "Soda",
        ["Milk"] = "Mleko",
        ["Cooked Meat"] = "Usmażone mięso",
        ["Bag"] = "Torba",
        ["Bush"] = "Krzak",
        ["Safe"] = "Sejf",
        ["Trap"] = "Pułapka",
        ["Bandage"] = "Bandaż",
        ["Medic Kit"] = "Zestaw medyczny",
        ["First Aid Kit"] = "Zestaw pierwszej pomocy",
        ["Medic Bag"] = "Torba medyczna",
        ["Painkiller"] = "Lek przeciwbólowy",
        ["Morphine"] = "Morfina",
        ["Blood Bag"] = "Worek krwi",
        ["WireFence"] = "Drut kolczasty",
        ["Sandbag"] = "Worki z piaskiem",
        ["Tent"] = "Namiot",
        ["Empty Water Boottle"] = "Pusta butelka wody",
        ["Silencer"] = "Tłumik",
        ["Clothing"] = "Ubranie",
        ["Helmet"] = "Hełm",
        ["Vest"] = "Kamizelka",
        ["Assault Pack (ACU)"] = "Plecak ACU",
		["Bag"] = 'Torba',
		["Alice Pack"] = 'Plecak Alice',
		["Mountain Backpack"] = 'Plecak Górski',
		["Czech Backpack"] = "Plecak Czech",
		["Coyote Backpack"] = "Plecak Kojot",
        ["Military Backpack"] = "Plecak Militarny",
        ["Camouflage Clothing"] = "Przebranie Kamuflujące",
		["Civilian Clothing"] = "Przebranie Cywila",
		["Survivor Clothing"] = "Przebranie Ocalałego",
		["Ghillie Suit"] = "Kombinezon Ghillie",
		["Reabel Clothing"] = 'Przebranie Rebelianta',
		["Woman Clothing"] = 'Przebranie Ocalałego [F]',
		["Military Clothing [F]"] = "Przebranie Wojskowe [F]",
		["Ghillie Suit [F]"] = "Kombinezon Ghillie [F]",
		["Kombinezon X"] = "Kombinezon X",
		["Diver Suit"] = "Przebranie nurka",
        ["Armor"] = "Zaloz Armor","Pancerz",
        ["Helmet [75%]"] = "Hełm [75%]",
		["Helmet [50%]"] = "Hełm [50%]",
		["Helmet [25%]"] = "Hełm [25%]",
		["Mossy Helmet"] = "Hełm Mossy",
		["Mossy Helmet [80%]"] = "Hełm Mossy [80%]",
		["Mossy Helmet [60%]"] = "Hełm Mossy [60%]",
		["Mossy Helmet [40%]"] = "Hełm Mossy [40%]",
		["Mossy Helmet [20%]"] = "Hełm Mossy [20%]",
		["Mossy Helmet [10%]"] = "Hełm Mossy [10%]",
		["Police Vest"] = "Kamizelka policyjna",
		["Police Vest [75%]"] = "Kamizelka policyjna [75%]",
		["Police Vest [50%]"] = "Kamizelka policyjna [50%]",
		["Police Vest [25%]"] = "Kamizelka policyjna [25%]",
		["Tactical Vest"] = "Kamizelka taktyczna",
		["Tactical Vest [80%]"] = "Kamizelka taktyczna [80%]",
		["Tactical Vest [60%]"] = "Kamizelka taktyczna [60%]",
		["Tactical Vest [40%]"] = "Kamizelka taktyczna [40%]",
		["Tactical Vest [20%]"] = "Kamizelka taktyczna [20%]",
		["Tactical Vest [10%]"] = "Kamizelka taktyczna [10%]",
    }
}


function GetTextLang(lang, text)

    if TextsTable[lang][text] then return TextsTable[lang][text] end
    return false
end