addCommandHandler("kontener", function(player) --Ex: /spawn bobcat
	if isObjectInACLGroup("user."..getAccountName(getPlayerAccount(player)), aclGetGroup("Admin")) or isObjectInACLGroup("user."..getAccountName(getPlayerAccount(player)), aclGetGroup("Pomocnik")) then
		local x,y,z = getElementPosition(player);		
		local kontener = createObject(3570,x, y, z,0,0,0)
		local tentCol = createColSphere(x, y, z, 5)
		setElementData(tentCol, "parent", kontener)
		setElementData(kontener, "parent", tentCol)
		setElementData(tentCol, "kontener", true)
		setElementData(tentCol, "MAX_Slots", 2000000)
		setElementData(tentCol, "Coyote Backpack", 50)
		setElementData(tentCol, "Tire", 100)
		setElementData(tentCol, "Engine", 50)
		setElementData(tentCol, "Milk", 50)
		setElementData(tentCol, "Pizza", 50)
		setElementData(tentCol, "Burger", 50)
		setElementData(tentCol, "Soda Bottle", 50)
		setElementData(tentCol, "M4A1-S", 50)
		setElementData(tentCol, "G36C", 50)
		setElementData(tentCol, "AK-47", 50)
		setElementData(tentCol, "MG-34", 30)
		setElementData(tentCol, "AWP", 50)
		setElementData(tentCol, "M4A1-S Mag", 80)
		setElementData(tentCol, "MG-34 Mag", 40)
		setElementData(tentCol, "G36C Mag", 100)
		setElementData(tentCol, "AWP Mag",50)
		setElementData(tentCol, "AK-47 Mag", 90)
		setElementData(tentCol, "Military Backpack", 50)
		setElementData(tentCol, "Painkiller", 50)
		setElementData(tentCol, "Toolbox", 50)
		setElementData(tentCol, "Night Vision Goggles", 100)
		setElementData(tentCol, "Morphine", 50)
		setElementData(tentCol, "Infrared Goggles", 60)
		setElementData(tentCol, "Medic Kit", 30)
		setElementData(tentCol, "Medic Bag", 30)
		setElementData(tentCol, "Bandage", 50)
		createBlipAttachedTo(kontener,33)
		outputChatBox(" === #ff9900Event walka o kontener #ffffff===",root,255,255,255, true)
		outputChatBox(" === #ff6633W kontenerze znajduje się spory zapas amunicji, częsci do pojazdów, prowiantu i medykamentow! #ffffff===",root,255,255,255, true)
	end
end);